### ISSUE TITLE
Document how to install development version of foreman-ansible-modules

### ISSUE THREAD

**Issue by markgraf** [theforeman/foreman-ansible-modules#1018]
##### SUMMARY
I try to install the development-version of the foreman-ansible-modules following [standard procedure](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-a-collection-from-a-git-repository).  Installation fails, see below.

Please document how to install the development version of the foreman-ansible-modules.

##### ISSUE TYPE
 - Documentation

##### ANSIBLE VERSION

```
ansible 2.9.10
  python version = 3.8.5 (default, Sep  5 2020, 10:50:12) [GCC 10.2.0]```
```

##### STEPS TO REPRODUCE

Have a requirements.yml like this:
```
---
collections:
  - name: https://github.com/theforeman/foreman-ansible-modules.git
    type: git
    version: develop
```

Run the install command:
```
$ ansible-galaxy collection install --ignore-errors -r collections/requirements.yml
Process install dependency map
ERROR! Collection artifact at '/home/marco/.ansible/tmp/ansible-local-126360f6gj6yxh/tmpu98ri6ri/foreman-ansible-modulesrdoar3kk.git' is not a valid tar file.
```

As an alternative, run:
```
$ ansible-galaxy collection install git+https://github.com/theforeman/foreman-ansible-modules.git,develop
Process install dependency map
ERROR! Invalid collection name 'git+https', name must be in the format <namespace>.<collection>. Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.
```
This fails because of the dashes in the repositories name.

##### EXPECTED RESULTS

I would expect the installation to succeed following the standard installation procedure.

##### ACTUAL RESULTS

Installation fails.  See above.

**Comment by mdellweg** [comment]
I do not see, why this should not work, but installing directly from git was never on my radar either.
ATM i'd suggest you to clone the repo & make sure your python has PyYAML available.
Then run:
```
make dist
ansible-galaxy collection install ./theforeman-foreman-1.3.0.tar.gz
```

**Comment by markgraf** [comment]
That did the trick. Thanks!

**Comment by markgraf** [comment]
Or not?

```
couldn't resolve module/action 'theforeman.foreman.smart_proxy'. This often indicates a misspelling, missing collection, or incorrect module path
```
I tried both 'theforeman.foreman.smart_proxy' and 'theforeman.foreman.foreman_smart_proxy', the latter taken from the example in the docs.

The other modules are working.

Install-issue? Or module-issue?

**Comment by mdellweg** [comment]
I don't know. Can you add -f to the install command?
Also, which docs refer to ’foreman_smart_proxy’? That is definitely wrong. Mind to send a PR?

**Comment by markgraf** [comment]
I `rm -rf`-ed the collection prior to install, that should be equivalent to `-f`?

'foreman_smart_proxy' was taken from the [Examples](https://theforeman.github.io/foreman-ansible-modules/develop/plugins/smart_proxy_module.html#examples)-section.
So I guess it should be just 'smart_proxy' then. Happy to PR if that is the case.

**Comment by mdellweg** [comment]
Is your ansible version really 2.9? Installing from git seems to be added to the docs only with 2.10. (Explaining why we didn't have it on the radar before...)

**Comment by mdellweg** [comment]
With ansible >= 2.10:
`ansible-galaxy collection install -f git+file:///home/user/projects/theforeman/foreman-ansible-modules`
worked like a charm.

**Comment by mdellweg** [comment]
@evgeni FYI seems like we can skip the "compilation" step starting with ansible 2.10. ;)

**Comment by evgeni** [comment]
Technically correct, but I'd prefer to keep that step to verify the compilation is correct

**Comment by mdellweg** [comment]
OTOH, if we tend to maintain support for this installation method, we can never reintroduce the `sed` part of the compilation.

**Comment by evgeni** [comment]
I think that's OK? ;)

**Comment by mdellweg** [comment]
Sure, this was meant to raise awareness.

**Comment by wbclark** [comment]
With ansible >= 2.10

`ansible-galaxy collection install -f git+file:///home/user/projects/theforeman/foreman-ansible-modules`

OR, with requirements.yml

```
---
collections:
  - name: https://github.com/theforeman/foreman-ansible-modules.git
    type: git
    version: develop
```

And then `$ ansible-galaxy collection install --ignore-errors -r collections/requirements.yml`

Failing that, this should work with all versions:

```
make dist
ansible-galaxy collection install ./theforeman-foreman-*.tar.gz
```

It would be helpful to update our docs with this information
