### ISSUE TITLE
Should 'state: present' be a default?

### ISSUE THREAD

**Issue by mdellweg** [theforeman/foreman-ansible-modules#103]
In the discussion
https://github.com/theforeman/foreman-ansible-modules/pull/79#discussion_r164454688
the question arose, whether the 'state' parameter of modules should have a default value 'present'.
After some investigation it seems to be usual with other ansible modules.

**Comment by akofink** [comment]
I am fine with making 'state: present' the default.

**Comment by Fobhep** [comment]
sounds good to me too
