### ISSUE TITLE
RFE: foremain/satellite-maintain module

### ISSUE THREAD

**Issue by bherrin3** [theforeman/foreman-ansible-modules#1038]
## Use Case

* SatQE has requirements to add packages as part of templatization that are not included or differ from OS-based packages that need to be installed with the Activation Key/Satellite release-specific package list
* Currently, there is not a `module` for `satellite-maintain` or `foreman-maintain` to add a list of packages or any other `*maintain` functionality

## Desired Feature

* The ability to use `*-maintain` as a module

## Module Use End Role desired Usage example
```
   - role: "{{ installer_scenario }}-maintain
      packages:
        - "{{ create_template_scenario_packages }}"
```
```
create_template_scenario_packages:
# Satellite QE Component Added packages
# Component: Authentication
# Reference: https://access.redhat.com/documentation/en-us/red_hat_satellite/6.7/html/administering_red_hat_satellite/chap-red_hat_satellite-administering_red_hat_satellite-configuring_external_authentication#integrating-satellite-with-red-hat-single-sign-on-for-external-authentication
  - keycloak-httpd-client-install
  - mod_auth_openidc
```

## Assistance that can be provided

* Can help to wrap the module as a role (complete module definition) in `satellite-ansible-compilation`
* Can help to write tests in `satellite-ansible-compilation` as well as PROD usecases in internal CI

## References

* [0] https://github.com/RedHatSatellite/satellite-ansible-compilation
* [1] https://access.redhat.com/documentation/en-us/red_hat_satellite/6.7/html/administering_red_hat_satellite/chap-red_hat_satellite-administering_red_hat_satellite-configuring_external_authentication#integrating-satellite-with-red-hat-single-sign-on-for-external-authentication

**Comment by evgeni** [comment]
Hey,

thanks for bringing this up.

Personally, I think this collection should focus on using the Foreman API and leave other tasks to another collection, mostly as this makes testing easier and allows the user to only install the tools they need. Nevertheless, the request of being able to interact with foremain-maintain is a valid one and we should discuss it (regardless of where the resulting code will end up).

Now to your explicit usecase: you want to be able to install additional packages on a Satellite (and well, Foreman/Katello) machine, while foremain_maintain is used with the package locking feature on, right? To the best of my knowledge, there are currently three ways to achieve that:
* `foreman-maintain package install <package>`
* `foreman-maintain package unlock && yum install <package> && foreman-maintain package lock`
* `yum install --disableplugin=foreman-protector <package>`

You can do the last one with Ansible's `yum` module by passing the `disable_plugin` parameter today already.
For the others we'd need custom code (be it module or role) that can check whether the packages in question need installation at all and if they do trigger the right foreman-maintain invocation. This is certainly possible, but feels a bit too much work if that'll be the only feature?

@ehelms do you have any plans on using f-maintain in the install/upgrade scenarios you've been thinking about?

**Comment by bherrin3** [comment]
@evgeni can you expand a little on:

```
whether the packages in question need installation at all and if they do trigger the right foreman-maintain invocation
```

The reason I ask is I am not sure if that logical statement is useful for the usecase I am stating.

Meaning, I am definitely installing Satellite-specific packages where I 100% *do not* have the configuration done for Authentication, via [1]. 

The reason? Templates.

Just want to ensure I am on the same page. Thanks, @evgeni !

**Comment by evgeni** [comment]
Sure.

I was aiming at the second invocation of that playbook you have. Then the `mod_auth_openidc` package is already installed and a call to "install mod_auth_openidc" should be a NOOP, right? If you don't want this to be a noop, then you can also just do `command: foreman-maintain package install mod_auth_openidc` and not bother with a module/role at all. But if you want it to be a NOOP in that case, you need logic to detect that the package actually needs installation.

**Comment by kedark3** [comment]
Ideally things should be able to detect NOOP for ansible modules, I know it is more work but believe its right approach for making things idempotent.

**Comment by bherrin3** [comment]
Talked to @evgeni off-issue and it appears that `foreman-maintain` is more of a RHEL/Sat specific feature. I also agree that implementing the whole code-base and solution set fot `foreman-maintain` is no small ask, nor am I sure it is useful.

That is where I will and wanted to back-up and ask @ehelms what, if any, use there is here.

For a short-term solution, I would use the `yum` based solution and I can write a role for that and I could contribute it to `satellite-ansible-compilation` as a "good enough for where we are in the product cycle" solution.

However, digging in a writing a modular module... I am not sure there is something here where scope and LoE makes sense.

@ehelms , can you help me make sense if there is anything here worth pursuing (no matter what project) or if this is really a NOOP and "just write a wrapper `yum` role for this usecase`?

**Comment by ehelms** [comment]
First note, I finally took this as a hint to escalate my idea to an RFC (https://community.theforeman.org/t/rfc-operations-ansible-collection/20971).

Second note, I do think @evgeni is a good idea in the short term for that specific, and more widely needed use case. However, if I look at the long term where additional operations (e.g. backup, restore) that are run through foreman-maintain are performed, there maybe be some benefit to turning maintain into a module for re-use.

**Comment by bherrin3** [comment]
I believe, with that being the case, this specific issue can be marked as resolved as we have reasonable short- and long-term solutions for this.

Thank you for hearing my input. I appreciate it.
