### ISSUE TITLE
Libvirt compute resource should support set_console_password

### ISSUE THREAD

**Issue by ares** [theforeman/foreman-ansible-modules#1052]
##### SUMMARY
Many times I disable setting console password for VMs, I want to easily connect to their VNC. Especially on demo or dev setups. compute_resource modules does not allow that. The API attribute is called `set_console_password` and must be one of: true, false, 1, 0. It's only available for libvirt and VMware.

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
For reference, the api description is here: https://theforeman.org/api/2.2/apidoc/v2/compute_resources/create.html

We should go over it completely and sync up the possible parameters.
