### ISSUE TITLE
The documentation should better describe the difference between a repository and repository_set

### ISSUE THREAD

**Issue by ares** [theforeman/foreman-ansible-modules#1059]
##### SUMMARY

It took me a while and question on IRC to figure, repository_set stand for RH repository. I'd suggest to modify the docs in a way

1) `repository_set – Enable/disable Repositories in Repository Sets` => `repository_set – Enable/disable Red Hat Repositories`
2) `repository – Manage Repositories` => `repository – Manage non RH Repositories` or even `repository – Manage Custom Repositories`
3) the repository detail should mention in synopsis, that for managing RH repositories, please use repository_set module.

##### ISSUE TYPE
 - Documentation

Not sure what the correct nomenclature should be, but some if the suggestion could simplify the first timer experience.

**Comment by evgeni** [comment]
`repository` *can* manage certain aspects of RH repos, like the download policy, so it's not all black and white, but yeah, the r_set string needs much improvement
