### ISSUE TITLE
How to reference IDs in practice?

### ISSUE THREAD

**Issue by MarkusTeufelberger** [theforeman/foreman-ansible-modules#107]
https://github.com/theforeman/foreman-ansible-modules/blob/master/test/test_playbooks/tasks/operating_system.yml for example is incomplete in the sense that it does not contain the necessary references to architecture(s), config/partition templates, media etc. (https://theforeman.org/api/1.15/apidoc/v2/operatingsystems/create.html) to create an actually usable operating system entry in foreman.

Writing something in Jinja2/YML to first fetch a list of architectures and then filter for the ID(s) of the one(s) you want to use is possible, but more complicated than probably necessary.

I'd like to be able to refer to any field that expects an ID by the corresponding exact name of that object instead (e.g. "architecture: x86_64" instead of "architecture_id: 2") and have the module or nailgun(?) do the conversion to IDs as expected by the foreman API in the background.

Alternatively, please publish some examples/snippets on how to get the ID of such objects reliably using parsing of task results to use it in further tasks.

**Comment by MarkusTeufelberger** [comment]
https://github.com/theforeman/foreman-ansible-modules/blob/bde0f2d5f3f6aa37f4bb275454ad19b87c4493e6/module_utils/ansible_nailgun_cement.py#L170

seems to be related...

**Comment by mdellweg** [comment]
This is at least related to #108 . In the 'new' modules, you can specify entities _only_ by _names_, however. Do you still think, we can close this one?

**Comment by MarkusTeufelberger** [comment]
I guess it can be closed, since the question is answered (you can't reference IDs at all).
