### ISSUE TITLE
Upstreaming to Ansible core: When?

### ISSUE THREAD

**Issue by MarkusTeufelberger** [theforeman/foreman-ansible-modules#108]
The foreman plugin in Ansible only supports a single(!) API call:

https://github.com/ansible/ansible/blob/841cb0e6a4d4c11b137075e4b16efd500c69b6cd/lib/ansible/modules/remote_management/foreman/foreman.py#L145-L149

This repository contains at least modules for more API calls and objects and makes their parameters more explicit as well as supporting a few comfort functions. It would be great to have them available by default in Ansible upstream.

**Comment by akofink** [comment]
Re: https://github.com/theforeman/foreman-ansible-modules/pull/114

**Comment by sean797** [comment]
Really we should get Nailgun packaged as RPM/Deb before pushing most of these modules into Ansible core.
I had a little look at that today but it looks like some Nailgun deps aren't packaged as RPM, `inflection` for example.

**Comment by akofink** [comment]
I only know a bit about packaging, but I think we can bundle all the dependencies that aren't already packaged into the nailgun package, right? We've recently un-bundled some stuff (pulp, I think), so that's what makes me think it's possible. Pulp would be a good project to collaborate with here since it's Python based and packaged for all our typical environments.

**Comment by akofink** [comment]
Also, perhaps this should be an issue on the Nailgun project? https://github.com/SatelliteQE/nailgun/issues/493

**Comment by Fobhep** [comment]
@mdellweg @akofink @sean797 @ehelms @evgeni 
A rather long time ago I committed the alpha-alpha version of our foreman-global-params module to the ansible core. https://github.com/ansible/ansible/pull/24939
Very recently I was asked on the very same PR whether or not I am still interested in getting it merged.
IMHO it's rather contra-productive to get now code without `cement` into the Ansible core, especially since it will then probably take forever to get rid of it there again.
Anyways I am curious about your opinion and would like to use this opportunity to "warm" up the discussion on going upstream

**Comment by akofink** [comment]
The ideas are not mutually exclusive, are they?

IMO committing these modules to Ansible core could happen at any time; however, I think there needs to be some effort to understand and enforce Foreman-Nailgun compatibility from within the modules or cement. Ideally, users of this in Ansible core should find that it 'just works' with any version of Foreman (or Satellite) they point it to (back to Foreman ~1.15).

**Comment by Fobhep** [comment]
no - they are certainly not mutually exclusive - I also like your approach @akofink 
My point is not so much whether or not it should be done, but to make sure we have certain conditions before we do it and to define them properly.

I have a feeling the Ansible projekt is a bit sluggish - simply due to its size - and I think sloppy start conditions could turn out into a chaos.
My feeling comes not from having acutally a module upstream, but rather from the reaction time to PRs in general that I observe(d).

**Comment by ericsysmin** [comment]
So, experience uploading modules to Ansible in the past, it's a long wait process and customers usually won't get any new fixes in your code until either they install and compile themselves or wait for releases. IMO this is inefficient and cumbersome, and is easier to just release roles with latest patches as library, and module_utils folders work. I have a pending pull that can with little change actually allow it to work both ways.

**Comment by mdellweg** [comment]
I do expect some friction from providing different 'official' versions of these modules with diverging apis. IMHO it is easier to sell this as an ever evolving toolbox if it were not fixed to ansible release cycles.

**Comment by ericsysmin** [comment]
We did encounter some issues early on in our release idea but eventually Ansible staff realized it does allow supported modules from lets say, Company A to make sure that their products were always supported by Ansible at any part of the release process.

Are any of you going to be at AnsibleFest 2018 in Austin?

**Comment by MarkusTeufelberger** [comment]
I maintain a module and review PRs in a namespace upstream as a community member - in general I'd say merge speed mostly depends on the contributors, not so much on the project. PRs for community modules can be merged quite quickly, especially if there are already a few people out there that can do the reviews and sign off on changes.

Having a "bleeding edge" version available in galaxy and a more stable version upstream is of course an option. Ansible releases relatively fast though, it's not like you have to wait years for an update. The reality is currently that there IS an upstream "foreman" module and it is bad.

AnsibleFest is on the wrong continent for me, sorry.

**Comment by ehelms** [comment]
Weighing in here based on my own thoughts and some conversations I've had with Ansible maintainers. First, I think we can all agree that the ideal scenario is making it easy and natural for users to acquire and use these great modules in an infrastructure as code manner. From reading above, and my own thoughts, I see 4 possible strategies:

 1) Leave this repository as is and advertise how to get the modules through use of git and package manager to get the python dependencies
 2) Turn this into a role and bundle it up into galaxy
 3) Move the contents of this repository into Ansible core repository and decommission this git repo
 4) Treat Ansible core as a snapshot of the modules, and on a regular basis transfer updates to the repository while doing core development here
 5) Develop modules here and graduate them out to Ansible core

I think #2 and #1 are essentially the same with #2 providing another slightly more Ansible method to acquire the modules. 

Option #3 moves everything into a pure Ansible way of doing development and updates to the modules. There is a potential uptick in contributions through this method as users who are familiar with Ansible know to go to the Ansible core repository to report issues and make changes to modules. I am aware that the Ansible team is trying to make module maintenance easier by looking at more automation for contributors and potentially breaking groups of modules out into their own supported Ansible repositories.

Option #4 attempts to bridge the gap by focusing development of modules here while providing snapshots to users to use in the traditional way. This would suffer from contributors wanting to make changes into Ansible core repository and keeping that in sync with changes made here.

Option #5 splits maintenance across the two repositories but would not suffer from changes made in one not making it to the other. This git repository would serve as a test and playground for new modules and we would need some graduation criteria. Changes to the cement would make this troublesome as well.

In all cases, users must still acquire Nailgun whether through pip or if we natively package it for certain OSes.

The upside of going the pure Ansible core route is that we live in that world, we learn about it, we potentially can help to make it better, users can get modules directly and we possibly get more contributors. The biggest downside to me is around support matrix of what versions of the server do the modules support. However, I think thats a general issue we need to solve in parallel.

**Comment by akofink** [comment]
I think I'd also vote for option 3, as it's the ultimate goal anyway.

**Comment by sean797** [comment]
I'd also like to add option 6 to the mix, though I'm not sure how I feel about it yet. 

Package up our modules, ship them via foreman-packaging. They can drop out modules and module_utils into the correct path for each distro. Just like ansible does for its own modules.

From a user it's like installing an "add-on" to ansibel providing extra modules.

**Comment by ehelms** [comment]
Option 6 does help provide maintained development methods with delivery of modules at the same cadence as Foreman itself. With the downside of not being delivered automatically with Ansible and in the same cadence as other modules.

I feel like we've reached a point where we've discussed this a few times, made good points here and there and now need to come together to make a choice and proceed with it. If we pick the wrong one, we'll figure that out and can correct course.

**Comment by sean797** [comment]
@ehelms agreed, let's make a choice and do it. For the purposes for holding a vote, I've created https://community.theforeman.org/t/how-to-ship-ansible-modules/11541

**Comment by sean797** [comment]
I'm going to close this as we are in the process of creating an Ansible Collection
https://github.com/theforeman/foreman-ansible-modules/milestone/1

See, https://galaxy.ansible.com/docs/contributing/creating_collections.html for more info. Thanks everyone, for all your input.
