### ISSUE TITLE
foreman_location can't mark a location as nested

### ISSUE THREAD

**Issue by MarkusTeufelberger** [theforeman/foreman-ansible-modules#109]
Let's say I have a general location `USA` and want to have the nested locations `USA/West` and `USA/East` - it seems I'm not able to express this with foreman_location at the moment.

I'd like to propose a `parent` (default None) parameter that can be used to nest locations.

**Comment by akofink** [comment]
If you'd like to propose a feature in Foreman, please submit [a new feature issue](http://projects.theforeman.org/projects/foreman/issues/new) or post on our [community forum](https://community.theforeman.org/). This repository isn't really the proper place to have this conversation.

**Comment by MarkusTeufelberger** [comment]
This is not a feature in foreman (foreman can already nest locations), it is a feature missing in the ansible modules in this repository which do not expose the foreman feature.

**Comment by akofink** [comment]
Ooh, sorry. I didn't realize. :see_no_evil:
