### ISSUE TITLE
Changing the organization/location of existing hosts

### ISSUE THREAD

**Issue by eleanorcuallado** [theforeman/foreman-ansible-modules#1108]
##### SUMMARY
It seems to me there is, to this day, no way to change the organization and location of a pre-existing host when updating it via the module, forcing the use of an API call via get-url when trying to do said operation. From what I gathered from the code, the "organization" and "location" parameters in host are filters and not parameters to modify. 

It feels to me it wouldn't be too complicated to add as well, since the API allows to modify it directly (parameter names could be like "new_organization" or something?).

I came up on this usecase during a migration process and I don't actually know how often it is requires, but since it's easily done through a PUT api call I figure it should be present to offer the possibility?

I did not read through the entire backlog of conversations but did not seem to find any issue linked to this, but if there is a reason why it has not been done, do feel free to tell me; my playbook currently does the direct url call, so all in all it's mostly to simplify future use 😄 

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
Actually, this was recently fixed in https://github.com/theforeman/foreman-ansible-modules/pull/1092, but that's not part of a release yet.

**Comment by eleanorcuallado** [comment]
Oh thanks! Guess I didn't check the pull requests ^^"

It'll be part of the next release then?

**Comment by evgeni** [comment]
That's the plan, yeah.

You can also patch your current install (only the change to `plugins/module_utils/foreman_helper.py` is required) or build yourself a snapshot release by cloning the repo and calling `make dist`.

**Comment by eleanorcuallado** [comment]
Okay, thanks a lot!
