### ISSUE TITLE
organizations role

### ISSUE THREAD

**Issue by willtome** [theforeman/foreman-ansible-modules#1109]
##### SUMMARY
Role for creating/managing organizations via variables.
(eg. https://github.com/redhat-cop/tower_configuration/tree/devel/roles/organizations)

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
I must say, I personally am a big opponent of multi-org setups as they are hard to manage and get right. And thus would like to avoid making such setups too easy to create. Won't block on my opinion, but would like y'all to think about it :)

**Comment by ehelms** [comment]
Are you saying you would opt for no organization role or just not a role that allows multiple orgs in one data structure to be defined?

**Comment by evgeni** [comment]
I'd go with no org role, as having one that just proxies the module seems also weird?

**Comment by ehelms** [comment]
Saves the user from having to write their own role to handle organization creation and can just import one. By not providing a role, I do not think we are necessarily preventing users from using multi-org, and making it harder for them does not mean they will avoid it. I do tend to think that a single org based role makes sense given that everything is scoped on organization.

**Comment by wbclark** [comment]
> I must say, I personally am a big opponent of multi-org setups as they are hard to manage and get right. And thus would like to avoid making such setups too easy to create. Won't block on my opinion, but would like y'all to think about it :)

That may be true but for some users they are unavoidable (manifests tied to separate accounts, etc). More to the point: Katello provides organizations, RBAC, and so on for these users; my opinion is we should provide the tools to manage them.

**Comment by evgeni** [comment]
> Saves the user from having to write their own role to handle organization creation and can just import one. By not providing a role, I do not think we are necessarily preventing users from using multi-org, and making it harder for them does not mean they will avoid it. I do tend to think that a single org based role makes sense given that everything is scoped on organization.

I'd argue that one doesn't need a role to use a module, and you'd have to write a playbook either way, so the writing would be identical (if we do a single-org role).

But then again, the Installer already creates an Org for us… ;)

> More to the point: Katello provides organizations, RBAC, and so on for these users; my opinion is we should provide the tools to manage them.

We do provide the module.

That all said, I won't refuse to have a role, even a multi-org one, just saying this is inviting the users to the wrong workflow.
