### ISSUE TITLE
What does present_with_defaults do in foreman_operating_system?

### ISSUE THREAD

**Issue by MarkusTeufelberger** [theforeman/foreman-ansible-modules#111]
What's the difference between `present` and `present_with_defaults`? Also why are there 2 modules (`foreman_operating_system` and `foreman_os_default_template`) that seem to do very similar things?

**Comment by mdellweg** [comment]
`foreman_operating_system` does the obvious (managing the existence and parameters of OSes).
`foreman_os_default_template` controls the _many-to-many-to-one_ ralation of which _template_ of a given _kind_ is the default choice for a given _operating system_. This association has to be set in a separate call to the foreman API, after marking the availability of the _template_ to the _operating system_. This closely resembles the steps needed to be carried out in the GUI.
For `present_with_defaults` (which is in desperate need of a better name) see #30 .
