### ISSUE TITLE
Role Variable Prefix

### ISSUE THREAD

**Issue by willtome** [theforeman/foreman-ansible-modules#1118]
##### SUMMARY
This issue is to open the discussion around variable naming convention for roles. Currently, "generic" variable names are used (eg. `server_url`, `username`, `manifest`, etc). This could lead to conflicting variables during runtime between other roles, facts, or extra_vars. I propose roles use variables with the prefix `foreman_` to "namespace" vars used by these roles.

Current state example:
```
server_url: https://satellite.example.com
username: admin
password: password
organization: "Default Organization"
manifest_path: /tmp/manifest.zip
activation_keys:
          - name: "Basic Activation Key"
```

Future State Example:
```
foreman_server_url: https://satellite.example.com
foreman_username: admin
foreman_password: password
foreman_organization: "Default Organization"

foreman_manifest_path: /tmp/manifest.zip

foreman_activation_keys:
          - name: "Basic Activation Key"
```

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
Hey @willtome!

Thanks for raising this. I must admit I never liked how Ansible does (not) allow easy namespacing of variables by default. But oh well, here we are.

May I ask for a bit more background of your environment? Do you have one single `vars.yml` that is loaded by all playbooks? Or does Tower inject them somehow "too globaly"?

The reason I am asking is: when we initially designed this, we did talk about prefixes to namespace between *our* roles, but never about completely others. And not having a `foreman_` prefix seemed natural, as this reduces confusion when used  in Satelilte environments.

The trail of thought was: well, the user will be having one (or multiple) playbook(s) that are managing their Foreman/Satellite, and the common things they will need is the "url", "username" etc, so those should be named the same for all roles (granted, this would also be the case when we prefix them with `foreman_`).

But we might need to bite the bullet and add that prefix, confusing Satellite users (or making playbooks not work across both systems, which also sucks)

**Comment by willtome** [comment]
@evgeni many of the use cases I currently have are for provisioning. This leads to single or multiple variable files that define all of the configurations for a deployment and seek to reduce the number of bespoke playbooks required by using these and other roles. It is hard to guarantee that a set of variables will only exist in a play being run against a foreman. For example, the same variables used to configure foreman may also be used to register hosts correctly and enable the proper repositories.

Additionally, since the modules interact over API, having orchestrated steps (ie. add a host to a host group) may be run as part of a play that doesn't run on the foreman host itself. This could introduce a large number of variables that are unrelated to the foreman and cause conflict.

The upstream/downstream challenge is another can of worms. Maybe consistently only using `foreman_` when it can be replaced with `satellite_` would help. I recognize that the prefix is extra overhead and it bothers me as well but at the end of the day provides a safer and more predictable user experience.

**Comment by gundalow** [comment]
The lack of namespace is a feature (or bug) depending on your view of the world.

We generally suggest
Proper variable naming can make plays more readable and avoid variable name conflicts
* Use descriptive, unique human-meaningful variable names
* Prefix role variables with it’s "owner" such as a role name or package

Source: http://ansible.github.io/community/decks/ansible-best-practices.html#/13

**Comment by evgeni** [comment]
Thanks!
@ehelms will explore the branding side and then we'll most probably add a `foreman_` prefix across the board.

**Comment by ehelms** [comment]
The Satellite team desires to brand the variable names when they package it up if we go with the `foreman_` namespacing route. While I think the consensus of the developer base is to avoid `foreman_` everywhere, the Ansible ecosystem and users are convincing enough to make that change. So we will make that switch across the board to prefix variables with `foreman_` and the likelihood is any downstream users will have to adapt anything written against FAM to use a different variable set if using the Satellite collection. That is, for example, foreman_username would become satellite_username. Hopefully this does not cause too much pain for users building roles and playbooks against FAM hoping to use them against Satellite. And that this change satisfies the needs of Tower users.

**Comment by mdellweg** [comment]
Well maybe you can add `<branding>_username: "{{ foreman_username }}"` (or the other way around) somewhere in groupvars to reuse portable playbooks.
