### ISSUE TITLE
Better overview on existing/missing Foreman API modules

### ISSUE THREAD

**Issue by MarkusTeufelberger** [theforeman/foreman-ansible-modules#113]
The following Foreman API resources exist according to https://theforeman.org/api/1.17/

- [ ] Architectures
- [x] ~~Audits~~ - readonly
- [ ] Auth source ldaps
- [ ] Autosign
- [ ] Bookmarks
- [x] Common parameters - [foreman_global_parameter](https://github.com/theforeman/foreman-ansible-modules/blob/master/modules/foreman_global_parameter.py)
- [ ] Compute attributes
- [x] Compute profiles - [foreman_compute_profile](https://github.com/theforeman/foreman-ansible-modules/blob/master/modules/foreman_compute_profile.py)
- [x] Compute resources - [foreman_compute_resource](https://github.com/theforeman/foreman-ansible-modules/blob/master/modules/foreman_compute_resource.py)
- [ ] Config groups
- [ ] Config reports
- [ ] Config templates
- [x] ~~Dashboard~~ - readonly
- [x] Domains - [foreman_domain](https://github.com/theforeman/foreman-ansible-modules/blob/master/modules/foreman_domain.py)
- [ ] Environments
- [ ] External usergroups
- [x] ~~Fact values~~ - readonly
- [ ] Filters
- [x] ~~Home~~ - readonly
- [ ] Host classes
- [ ] Hostgroup classes
- [ ] Hostgroups
- [ ] Hosts
- [ ] Http proxies
- [ ] Images
- [ ] Interfaces
- [x] Locations - [foreman_location](https://github.com/theforeman/foreman-ansible-modules/blob/master/modules/foreman_location.py)
- [x] ~~Mail notifications~~ - readonly
- [ ] Media
- [ ] Models
- [x] Operating systems - [foreman_operating_system](https://github.com/theforeman/foreman-ansible-modules/blob/master/modules/foreman_operating_system.py)
- [x] Organizations - [foreman_organization](https://github.com/theforeman/foreman-ansible-modules/blob/master/modules/foreman_organization.py)
- [x] Os default templates - [foreman_os_default_template](https://github.com/theforeman/foreman-ansible-modules/blob/master/modules/foreman_os_default_template.py)
- [ ] Override values
- [ ] Parameters
- [x] ~~Permissions~~ - readonly
- [ ] Personal access tokens
- [x] ~~Plugins~~ - readonly
- [x] Provisioning templates - [foreman_provisioning_template](https://github.com/theforeman/foreman-ansible-modules/blob/master/modules/foreman_provisioning_template.py)
- [x] Ptables - [foreman_ptable](https://github.com/theforeman/foreman-ansible-modules/blob/master/modules/foreman_ptable.py)
- [ ] Puppet hosts
- [ ] Puppetclasses
- [x] Realms
- [ ] Reports
- [ ] Roles
- [x] Settings
- [ ] Smart class parameters
- [ ] Smart proxies
- [ ] Smart variables
- [ ] Ssh keys
- [x] ~~Statistics~~ - readonly
- [ ] Subnets
- [x] ~~Tasks~~ - readonly
- [ ] Template combinations
- [x] ~~Template kinds~~ - readonly
- [ ] Usergroups
- [ ] Users

Not all of these are really useful/interesting for Ansible modules. Some only support GET parameters, so they might be interesting for extracting facts or variables or asserting on their content, but they can't really be configured for example.

Still some modules are missing for my use case (manage/store the configuration of a Foreman instance in Ansible). It would be nice to have a list like the above for Foreman and Katello also in the README.md file to get a quick overview what's already possible and what not.

I can open a PR for this, if you like.

**Comment by MarkusTeufelberger** [comment]
Hm, I worked on getting the same overview on Katello APIs (https://theforeman.org/plugins/katello/3.5/api/index.html), but they are mostly the same ones as Foreman with a few key differences (e.g. Katello's `Organization` shadows the Foreman one). I already had issues using the modules here on a Vagrant box running Forklift that had no Katello installed...

Is the actual API that the modules here try to make available in Ansible only the Katello one?

**Comment by akofink** [comment]
We should probably structure the documentation as Foreman + Plugins. It'd be a good start to have all of Foreman.

**Comment by MarkusTeufelberger** [comment]
Then there's `redhat_manifest` which is a bit of a weird case (see the discussions in #71) and these 4 "action modules" which seem rather non-idempotent and don't seem to have a counterpart in the actual API. They also have a very low chance of getting upstreamed.

I'm really not sure about these...

`katello_upload` and `katello_manifest` sound like they could be made idempotent, with `katello_sync` and `katello_content_view_publish` this sounds near impossible. Probably these functionalities should be added as parameters to the respective modules (e.g. a `force` or `publish` parameter in `katello_content_view` that publishes the content view every time or once it has been changed).

**Comment by MarkusTeufelberger** [comment]
Closing - Foreman version is not specified for these modules so this is a running target anyways.
