### ISSUE TITLE
Increase timeout for host creation

### ISSUE THREAD

**Issue by erezzarum** [theforeman/foreman-ansible-modules#1156]
When provisioning a host that rely on a finish script, the finish script can take very long time to finish.

As i understand currently the task timeout is set to about 5m (task_timeout=60, task_poll=4)
After about 5m i receive this: "Error while performing create on hosts: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"

I receive this error after about 5m (timed).

It will be a good idea to either let the user set a timeout or hard code a timeout (module.task_timeout) to a larger value as the one in the "repository_sync" module.

**Comment by mdellweg** [comment]
I know, that we have an increased timeout in the sync module. You could take a look there if you want to submit a patch.

**Comment by evgeni** [comment]
Host creation is a sync action in Foreman, so increasing the timeout we have for foreman *tasks* won't help here. We'd have to tell requests to wait longer, which I really don't like.

**Comment by erezzarum** [comment]
@evgeni You mean the "requests" python module? If this, then i could not find anywhere where a timeout is set, and by default if no timeout is set the requests is set to "None"

**Comment by evgeni** [comment]
Yes, that's what I meant.

It could also be Apache or a firewall terminating the connection after 5 minutes. Now reading your exact error, I agree it's not requests - that gives a different Exception when a timeout occurs.

**Comment by erezzarum** [comment]
Apache should not be terminating the connections, perhaps using keep-alive headers is needed?
Editing: It does not happen when using hammer

**Comment by evgeni** [comment]
I'll have a look what hammer does differently.

**Comment by erezzarum** [comment]
@evgeni I'm sorry, but usually i don't open issues without checking 100%.
I was moving all my ansible environments to run under docker and it seems this what has caused it.
I have just verified and created a virtualenv and it does not happen there, only under "docker run".
So this is not a foreman ansible module issue.
Sorry for the interruption.

**Comment by evgeni** [comment]
No worries, as long as it's fixed now, I am happy :)
