### ISSUE TITLE
Sync multiple products simultaneously

### ISSUE THREAD

**Issue by wbclark** [theforeman/foreman-ansible-modules#1158]
Currently when syncing repositories using the module `theforeman.foreman.repository_sync` I have to define either one ansible task per repository or one ansible task per product. Furthermore, each ansible task runs until the foreman task is completed, which under some circumstances takes considerable time.

It would be a significant improvement to define an option like `wait_for_completion: false` so that the play can continue while large repository syncs have been initiated. This way several repos across multiple products can be synced in parallel, as is supported by Katello, which would greatly reduce the execution time for plays which sync multiple large repositories.

**Comment by mdellweg** [comment]
IIRC we removed such a feature deliberately, because it was a pain.
There is an ansible builtin method to send long running tasks to the background:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html
And i believe, that way, you can even gather their results later.
Be careful, you can easily DOS your katello if you start too many sync tasks at once.

**Comment by wbclark** [comment]
> IIRC we removed such a feature deliberately, because it was a pain.
> There is an ansible builtin method to send long running tasks to the background:
> https://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html
> And i believe, that way, you can even gather their results later.
> Be careful, you can easily DOS your katello if you start too many sync tasks at once.

I found the referenced commit at https://github.com/theforeman/foreman-ansible-modules/commit/82ae5ccdf077966101405ab83690d9b6c612d487#diff-47548be82ea3d1e662a5aa75cf36fd96d4e5d8ed7ac27c8f28cb1e7781dfabc2

It looks like an example was given using the built-in ansible method to syncs all repos asynchronously. From the looks of it I agree it was a bad example, and I argue my implementation at https://github.com/theforeman/foreman-ansible-modules/pull/1159 is different in a few key ways:

1. It's a feature built into the module that allows Ansible to treat 'foreman task is created' as the goal, rather than waiting for 'foreman task is complete'

2. It's disabled by default and preserves the current behavior for all existing roles and playbooks

3. Common pitfalls (don't sync 300 repositories simultaneously with this method) can be documented so users will avoid it, while on the other hand it greatly improves the usability and even performance (allowing more parallelism) in cases where users understand the tradeoffs and want to opt-in to the alternate behavior. It's particularly a large performance benefit when syncing a small number of large repositories (my exact use case)

**Comment by mdellweg** [comment]
I know, the syntax may be weird, but when using the ansible async methods, you can still continue with your playbook, but wait for the synced repos at some point to promote your content for example. I consider this to be the high level feature.

**Comment by wbclark** [comment]
Thanks @mdellweg , I will give it a try and report back my experience.

A few more areas to consider about it are

1. Some users may actually wish to have the Ansible task treated as complete while the Foreman task is still running (for example, the completed Ansible task could register something like a Task ID that they can monitor themselves). Without having tried it yet, I'm not sure if this is possible using Ansible's built in async option but will investigate.

2. There is also a definite case where we want to sync multiple products in parallel while also waiting for the tasks to fully complete, so expanding the module to accept multiple products seems like a must-have.

**Comment by wbclark** [comment]
>     2\. There is also a definite case where we want to sync multiple products in parallel while also waiting for the tasks to fully complete, so expanding the module to accept multiple products seems like a must-have.

Ok, it looks like `async_status` covers this case

**Comment by wbclark** [comment]
Repositories can be synced simultaneously using Ansible's async feature. An example of this is here: https://github.com/theforeman/foreman-ansible-modules/blob/2045c5edef5792d3235eb5c2b234ef08e3fa96b3/roles/content_rhel/tasks/main.yml#L31-L55

To wait for the syncs to complete before proceeding with further ansible tasks, the approach is https://github.com/theforeman/foreman-ansible-modules/blob/2045c5edef5792d3235eb5c2b234ef08e3fa96b3/roles/content_rhel/tasks/main.yml#L78-L94
