### ISSUE TITLE
Foreman tries to run Playbooks on loca, when i´m using the dellemc os6 collection

### ISSUE THREAD

**Issue by kevin972202** [theforeman/foreman-ansible-modules#1194]
I´m using Foreman 2.3 and Ansible 2.9. The Callback between them work fine. I want to do a Backup from a Switch Configuration. I integreated the Switch as unmanaged Host. If i run this Playbook foreman does a local connection and tries to run the Playbook on the local machine instead of connecting to the switch. When i run this Playbook normaly about the commandline of Terminal, it works fine. I created a host group wit alle this vars in the Playbook and run the Playbook without the vars on the Foreman Host instead on the Switchhost and ansible tired aswell to run the playbook on the local machine. But if i run command without the collection, it tries to connect with ssh. This is the Playbook:

    hosts: all
    tasks:

        name: backup
        vars:
            ansible_connection: ansible.netcommon.network_cli
            ansible_user: ansible
            ansible_become: yes
            ansible_become_method: enable
            ansible_network_os: dellemc.os6.os6

        dellos6_config:

        backup: yes
        backup_options:
        dir_path: /home/{{ inventory_hostname }}

This is the error:

1:
ansible-playbook 2.9.19
2:
config file = /usr/share/foreman-proxy/.ansible.cfg
3:
configured module search path = [u'/usr/share/my_modules']
4:
ansible python module location = /usr/lib/python2.7/dist-packages/ansible
5:
executable location = /usr/bin/ansible-playbook
6:
python version = 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]
7:
Using /usr/share/foreman-proxy/.ansible.cfg as config file
8:
setting up inventory plugins
9:
host_list declined parsing /usr/lib/ruby/bin/json_inventory.sh as it did not pass its verify_file() method
10:
Parsed /usr/lib/ruby/bin/json_inventory.sh inventory source with script plugin
11:
Loading callback plugin yaml of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/yaml.pyc
12:
[WARNING]: Skipping callback plugin '', unable to load
13:
Skipping callback 'actionable', as we already have a stdout callback.
14:
Skipping callback 'counter_enabled', as we already have a stdout callback.
15:
Skipping callback 'debug', as we already have a stdout callback.
16:
Skipping callback 'dense', as we already have a stdout callback.
17:
Skipping callback 'dense', as we already have a stdout callback.
18:
Skipping callback 'full_skip', as we already have a stdout callback.
19:
Skipping callback 'json', as we already have a stdout callback.
20:
Skipping callback 'minimal', as we already have a stdout callback.
21:
Skipping callback 'null', as we already have a stdout callback.
22:
Skipping callback 'oneline', as we already have a stdout callback.
23:
Skipping callback 'selective', as we already have a stdout callback.
24:
Skipping callback 'skippy', as we already have a stdout callback.
25:
Skipping callback 'stderr', as we already have a stdout callback.
26:
Skipping callback 'unixy', as we already have a stdout callback.
27:
Skipping callback 'yaml', as we already have a stdout callback.
28:

29:
PLAYBOOK: foreman-playbook-44656c4f-f8b9-475c-9640-62369bb82bed.yml ************
30:
Positional arguments: /tmp/foreman-playbook-44656c4f-f8b9-475c-9640-62369bb82bed.yml
31:
become_method: sudo
32:
inventory: (u'/usr/lib/ruby/bin/json_inventory.sh',)
33:
forks: 5
34:
tags: (u'all',)
35:
verbosity: 4
36:
connection: smart
37:
timeout: 10
38:
1 plays in /tmp/foreman-playbook-44656c4f-f8b9-475c-9640-62369bb82bed.yml
39:

40:
PLAY [all] *********************************************************************
41:
META: ran handlers
42:

43:
TASK [backup] ******************************************************************
44:
task path: /tmp/foreman-playbook-44656c4f-f8b9-475c-9640-62369bb82bed.yml:7
45:
<10.230.220.111> attempting to start connection
46:
<10.230.220.111> using connection plugin ansible.netcommon.network_cli
47:
<10.230.220.111> local domain socket does not exist, starting it
48:
<10.230.220.111> control socket path is /var/lib/foreman-proxy/ansible/pc/a87756e8ca
49:
<10.230.220.111> local domain socket listeners started successfully
50:
<10.230.220.111> loaded cliconf plugin ansible_collections.dellemc.os6.plugins.cliconf.os6 from path /usr/share/ansible/collections/ansible_collections/dellemc/os6/plugins/cliconf/os6.py for network_os dellemc.os6.os6
51:
<10.230.220.111>
52:
<10.230.220.111> local domain socket path is /var/lib/foreman-proxy/ansible/pc/a87756e8ca
53:
<10.230.220.111> Using network group action dellos6 for dellos6_config
54:
<10.230.220.111> ESTABLISH LOCAL CONNECTION FOR USER: foreman-proxy
55:
<10.230.220.111> EXEC /bin/sh -c '( umask 77 && mkdir -p "echo /tmp/ansible-local-7600ieqYxT"&& mkdir "echo /tmp/ansible-local-7600ieqYxT/ansible-tmp-1617876563.52-7609-82267792843100" && echo ansible-tmp-1617876563.52-7609-82267792843100="echo /tmp/ansible-local-7600ieqYxT/ansible-tmp-1617876563.52-7609-82267792843100" ) && sleep 0'
56:
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/dellos6/dellos6_config.py
57:
<10.230.220.111> PUT /tmp/ansible-local-7600ieqYxT/tmpKdn4dX TO /tmp/ansible-local-7600ieqYxT/ansible-tmp-1617876563.52-7609-82267792843100/AnsiballZ_dellos6_config.py
58:
<10.230.220.111> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-local-7600ieqYxT/ansible-tmp-1617876563.52-7609-82267792843100/ /tmp/ansible-local-7600ieqYxT/ansible-tmp-1617876563.52-7609-82267792843100/AnsiballZ_dellos6_config.py && sleep 0'
59:
<10.230.220.111> EXEC /bin/sh -c '/usr/bin/python3 /tmp/ansible-local-7600ieqYxT/ansible-tmp-1617876563.52-7609-82267792843100/AnsiballZ_dellos6_config.py && sleep 0'
60:
<10.230.220.111> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-local-7600ieqYxT/ansible-tmp-1617876563.52-7609-82267792843100/ > /dev/null 2>&1 && sleep 0'
61:
The full traceback is:
62:
File "/tmp/ansible_dellos6_config_payload_tu8t4pov/ansible_dellos6_config_payload.zip/ansible/module_utils/network/dellos6/dellos6.py", line 86, in get_config
63:
return _DEVICE_CONFIGS[cmd]
64:
fatal: [switchsz]: FAILED! => changed=false
65:
invocation:
66:
module_args:
67:
after: null
68:
auth_pass: null
69:
authorize: null
70:
backup: true
71:
backup_options:
72:
dir_path: /home/switchsz
73:
filename: null
74:
before: null
75:
config: null
76:
host: null
77:
lines: null
78:
match: line
79:
parents: null
80:
password: null
81:
port: null
82:
provider: null
83:
replace: line
84:
save: false
85:
src: null
86:
ssh_keyfile: null
87:
timeout: null
88:
update: merge
89:
username: null
90:
msg: unable to retrieve current config
91:
stderr: Unable to decode JSON from response to exec_command(show running-config). Received 'None'.
92:
stderr_lines:
93:

94:
PLAY RECAP *********************************************************************
95:
switchsz : ok=0 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0
96:

97:
Exit-Status: 2

**Comment by evgeni** [comment]
Ping @ares 

This sounds like a foreman_ansible issue, not a modules one?

**Comment by kevin972202** [comment]
I dont konw, If it is forman_ansible or the os6 collection. I only know If i Run any playbook in Foreman with the os6 collection it tries to Run in on the local machine. But If i Run a playbook without this collection it tries to make a Connection with SSH to the Switch. But i need the collection, because i have only dell Switches and if i Run any playbook against this Switch the Connection Interrupts when ansible tries to make any command. With the collection it does the Backup, Just with ansible without Foreman, but in Foreman_ansible it doesnt make a SSH Connection an tries to Run it on the local machine.
