### ISSUE TITLE
CV publish role

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#1209]
##### SUMMARY
we should have a role that accepts a list of CVs and just does a publish on them

similar, we probably also should have one that does a simple promote on a list?

##### ISSUE TYPE
 - Feature Idea

**Comment by bmarlow** [comment]
Please see PR [#1214](https://github.com/theforeman/foreman-ansible-modules/pull/1214)

**Comment by evgeni** [comment]
Also #1210

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-ansible-modules/pull/1210 was merged
