### ISSUE TITLE
Add arch option to theforeman.foreman.repository module

### ISSUE THREAD

**Issue by igramic** [theforeman/foreman-ansible-modules#1265]
##### SUMMARY
In Satellite GUI when we create product repository we can restrict that repository on specific OS version (rhel8, rhel7 ...) and architecture
It would be awesome if we could do same via theforeman.foreman.repository

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
from the API doc (of 4.1):

os_versions  - Identifies whether the repository should be disabled on a client with a non-matching OS version. Pass [] to enable regardless of OS version. Maximum length 1; allowed tags are: rhel-6, rhel-7, rhel-8

also interesting:

arch - Architecture of content in the repository

**Comment by evgeni** [comment]
@igramic implemented the `os_version` in #1266 - so we're only missing `arch` now.

**Comment by SimonLorentz** [comment]
Hello everyone,

is there a timeline, when we can expect this new feature?
Would be very cool for a project.

Best regards

**Comment by evgeni** [comment]
@SimonLorentz as you asked so nicely, feel free to try https://github.com/theforeman/foreman-ansible-modules/pull/1282 ;-)

**Comment by SimonLorentz** [comment]
@evgeni thanks, it seems to do nothing, no error, but also no action ^^

**Comment by evgeni** [comment]
Which Katello version are you running, and what would you expect to happen once you set that option?

**Comment by SimonLorentz** [comment]
I´m running against Satellite 6.9 with Katello 3.18.1.

![image](https://user-images.githubusercontent.com/50730652/132325632-af356b81-fcfe-4ea8-9461-d4333c07133d.png)

I would expect, that the arch is set in my repository, like the version.

**Comment by evgeni** [comment]
That parameter is only present in the Katello 4.0+ API: https://projects.theforeman.org/issues/31615

You actually should have gotten a warning from Ansible, that the parameter is not supported by your server. Something like "The following parameters are not supported by your server when performing update on repository: arch. They were ignored."

**Comment by SimonLorentz** [comment]
Ah okay yes I got it, my bad

**Comment by evgeni** [comment]
FWIW, I tried this against a Katello 4.1  installation, and it works exactly as you'd expect ;)
