### ISSUE TITLE
kt_activation_keys in parameters get duplicated

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#1268]
##### SUMMARY

if you pass

```
parameters:
  - name: kt_activation_keys
    value: lol
```

to `hostgroup`, you end up with the duplicate param error on the second run of the playbook, as the below code doesn't check if the param actually needs to be appended again

https://github.com/theforeman/foreman-ansible-modules/blob/604f60b884707ee25282155c1fe5b5f0146a943d/plugins/module_utils/foreman_helper.py#L320-L330

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### COLLECTION VERSION

```

```

##### KATELLO/FOREMAN VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by KoffiemokmetThee** [comment]
I have this problem as well. It would be nice if a parameter exists it would return "ok" in the Ansible run.

**Comment by evgeni** [comment]
@KoffiemokmetThee the cleanest solution should be to use the dedicated `activation_keys` parameter (which will get translated to the right Foreman parameter internally, and is working fine right now), but the syntax with `kt_activation_keys` should also work and we will fix that.

**Comment by evgeni** [comment]
@KoffiemokmetThee there is a patch in #1271 if you want to try it out :)

**Comment by Fodoj** [comment]
With 2.2.0 this bug still occurs to me - I have set kt_activation_keys via "params" and it breaks on a second run. I could not find dedicated "activation_keys" parameter in hostgroup.py - is it provided by HostMixing somehow?

**Comment by evgeni** [comment]
It's provided by the `HostMixin`, yeah:
https://github.com/theforeman/foreman-ansible-modules/blob/8fe622d1ae014fe7bf5b66239859cbc3ce351127/plugins/module_utils/foreman_helper.py#L306

let me spin up a fresh katello and try that out again.

**Comment by evgeni** [comment]
Hum, works for me.

Can you show me your playbook please?

I essentially do:

```yaml
- theforeman.foreman.hostgroup:
  …
  parameters:
    - name: kt_activation_keys
      parameter_type: string
      value: new_key

**Comment by evgeni** [comment]
I've added tests here: https://github.com/theforeman/foreman-ansible-modules/pull/1278

**Comment by Fodoj** [comment]
Basically the same:

```
parameters: "{{ hg.parameters | default(omit) }}"  
```

where hg has:

```
 parameters:
    - name: kt_activation_keys
      value: my-ket
   - name: another-param
     value: val
```


Difference is lack of "parameter_type" and multiple other params except besides kt_activation_keys. 

FYI I've switched to activation_keys and it works.

**Comment by evgeni** [comment]
Nope, neither dropping the `parameter_type`, nor adding another parameter helps reproducing it :(

But glad `activation_keys` works for you.
