### ISSUE TITLE
foreman_repository: Allow to configure download-concurrency

### ISSUE THREAD

**Issue by Thulium-Drake** [theforeman/foreman-ansible-modules#1273]
##### SUMMARY

Some repos may have resource restrictions that will cause timeouts with Pulp (possibly due to rate-limiting) when syncing repos.

The forum thread below suggested to set a download concurrency on those repos. However, the Ansible module currently is unable to do so.

https://community.theforeman.org/t/unable-to-sync-some-repositories-almalinux-in-this-case/24705/29

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
:+1: 

https://theforeman.org/plugins/katello/3.18/api/apidoc/v2/repositories/create.html defines it as `download_concurrency`

**Comment by Thulium-Drake** [comment]
Finally had a moment to dig into this :-) turns out to be a _really_ simple fix (see PR)

FWIW, you can't see the current value for download_concurrency via Hammer or the API, but you can get it when you run the following SQL query on the foreman database:

```
foreman=# select name,download_concurrency from katello_root_repositories;
                 name                 | download_concurrency 
--------------------------------------+----------------------
 Rocky8-AppStream-Base                |                     
 EPEL8-Base                           |                     
 Ansible-EL8-Ansible-2.9              |                     
 Rocky8-BaseOS-AppStream              |                    30
 Foreman-Tools-EL8-Base               |                     
 Foreman-Server-EL8-Foreman-Base      |                     
 Foreman-Server-EL8-Foreman-Plugins   |                     
 Foreman-Server-EL8-Katello-Base      |                     
 Foreman-Server-EL8-Katello-Candlepin |                     
 Foreman-Pulp-EL8-Base                |                     
 PowerDNS-EL8-Recursor-4.4            |                     
 PowerDNS-EL8-Authoratative-4.4       |                     
 Zabbix-EL8-Zabbix-5.4                |                     
 Foreman-Puppet-EL8-Puppet6           |                     
```

:-)
