### ISSUE TITLE
Can't record certain tests "No module named nailgun.config"

### ISSUE THREAD

**Issue by petebowden** [theforeman/foreman-ansible-modules#128]
Hitting an error recording certain tests. "No module named nailgun.config".

`$ make record_sync_plan
rm -f test/test_playbooks/fixtures/sync_plan-*.yml
pytest 'test/test_crud.py::test_crud[sync_plan]' --record
<snip>

FAILURES
<snip>

module = 'sync_plan', record = True

    @pytest.mark.parametrize('module', MODULES)
    def test_crud(module, record):
>       assert run_playbook_vcr(module, record=record) == 0
E       AssertionError: assert 2 == 0
E        +  where 2 = run_playbook_vcr('sync_plan', record=True)

test/test_crud.py:65: AssertionError
----------------------------------------------------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------------------------------------------------

PLAY [fixtures] ****************************************************************

TASK [Load server config] ******************************************************
ok: [fixtures]

TASK [Ensure organization 'Test Organization' is present] **********************
fatal: [fixtures]: FAILED! => {"changed": false, "msg": "No module named nailgun.config"}

PLAY RECAP *********************************************************************
fixtures                   : ok=1    changed=0    unreachable=0    failed=1

<snip>
make: *** [record_sync_plan] Error 1`

**Comment by mdellweg** [comment]
Pretty sure, this is the same as #127 
Can we close it?

**Comment by petebowden** [comment]
I'm guessing it's the same. I'll close.
