### ISSUE TITLE
template handling modules fail to read header comment

### ISSUE THREAD

**Issue by mdellweg** [theforeman/foreman-ansible-modules#130]
All template handling modules seem to fail reading the erb-comment that is meant as a header containing the template configuration if it is not the first thing in the template text.

This problem surfaced when trying to import the iPXE community templates, because they start with `#!gpxe`.

Should we simply adapt our regex to search for the first erb comment, or do we need to be more specific?

**Comment by akofink** [comment]
Looks like this is the 'proper' shebang. Seems we should support/adapt regex for it, right?

**Comment by mdellweg** [comment]
The problem is, that it is before the erb comment block. But as we are not going to "fix" the community templates for this one, we have to solve it here.
