### ISSUE TITLE
RFE: hostgroup_info

### ISSUE THREAD

**Issue by coec** [theforeman/foreman-ansible-modules#1331]
##### SUMMARY
The appears to not be a way to get hostgroup information via this Anisble collection

##### ISSUE TYPE
Create a plugin "hostgroup_info" that will allow, among other things, retrieving the hostgroup's parameters

**Comment by evgeni** [comment]
this has been fixed in https://github.com/theforeman/foreman-ansible-modules/commit/4089f6377605121604299e83afb4729c0b556a53
