### ISSUE TITLE
Hosts API to Reports API, why?

### ISSUE THREAD

**Issue by mpl241** [theforeman/foreman-ansible-modules#1366]
##### SUMMARY
Sometime after upgrading `theforeman.foreman` collection, the following warning was always displayed when using `theforeman.foreman.foreman` inventory plugin:

```
Failed to use Reports API, falling back to Hosts API: Error scheduling inventory report on foreman. Please check foreman logs!
```

It took some time to track this down, but I was able to figure out what generated the warning (`theforeman.foreman.foreman`) and what triggered the warning.

Some background, I configure Ansible to use a dedicated Satellite user to query Satellite for host inventory so I can avoid having credentials for an account with "lots" of permissions in a file.  The account had just enough permissions to collect the inventory for Ansible.

After spending a few hours deciphering `/var/log/foreman/production.log` entries, tripping over Foreman/Satellite API documentation, and trial-and-error, I determined the NEW minimum permissions required for `theforeman.foreman` inventory plugin to gather the inventory from Satellite using the reports API:

'''
$ hammer role filters --name "Ansible Inventory"
----|-----------------|--------|------------|-----------|-------------------|---------------------------
ID  | RESOURCE TYPE   | SEARCH | UNLIMITED? | OVERRIDE? | ROLE              | PERMISSIONS               
----|-----------------|--------|------------|-----------|-------------------|---------------------------
547 | ReportTemplate  | none   | yes        | no        | Ansible Inventory | view_report_templates     
550 | ReportTemplate  | none   | yes        | no        | Ansible Inventory | generate_report_templates 
551 | Host            | none   | yes        | no        | Ansible Inventory | view_hosts                
552 | (Miscellaneous) | none   | yes        | no        | Ansible Inventory | generate_ansible_inventory
----|-----------------|--------|------------|-----------|-------------------|---------------------------
'''

Although I am happy with getting to the bottom of the warning message, I was not happy with the new entries in the Satellite task list.  Considering Ansible can pull an inventory from Satellite on every run, I can see the task list filling-up with mostly unnecessary reports tasks.

'''
$ hammer task list --search "action = \"Render report Ansible - Ansible Inventory\""
-------------------------------------|--------------------------------------------|---------|---------|---------------------|---------------------|-------------------|------------
ID                                   | ACTION                                     | STATE   | RESULT  | STARTED AT          | ENDED AT            | OWNER             | TASK ERRORS
-------------------------------------|--------------------------------------------|---------|---------|---------------------|---------------------|-------------------|------------
9be02a01-3cd9-4bc3-a132-5f56acb4782c | Render report Ansible - Ansible Inventory  | stopped | success | 2022/03/23 16:15:19 | 2022/03/23 16:15:25 | ansible-inventory |            
3946097d-cf21-40e9-bdcd-c9ab2916d882 | Render report Ansible - Ansible Inventory  | stopped | success | 2022/03/23 16:05:17 | 2022/03/23 16:05:22 | ansible-inventory |            
b245097e-365b-4606-8873-4e3ee7a1be13 | Render report Ansible - Ansible Inventory  | stopped | success | 2022/03/23 16:03:08 | 2022/03/23 16:03:12 | ansible-inventory |            
9f578a47-5d9f-4ce9-a473-141ba53b6908 | Render report Ansible - Ansible Inventory  | stopped | success | 2022/03/23 16:01:50 | 2022/03/23 16:01:54 | ansible-inventory |            
5a7b5606-5842-4749-8c0b-310445c0e701 | Render report Ansible - Ansible Inventory  | stopped | success | 2022/03/23 16:01:20 | 2022/03/23 16:01:24 | ansible-inventory |            
-------------------------------------|--------------------------------------------|---------|---------|---------------------|---------------------|-------------------|------------
'''

Why is using the reports API more desirable then using the hosts API?  Pulling a report every time Ansible is run doesn't seem like an efficient way of gathering the inventory.

Also, there are some pretty large holes in the Foreman/Satellite API documentation regarding permissions, although I doubt it is foreman-ansible-modules problem.

Thanks for your help!
Matt

Reference: https://github.com/theforeman/foreman-ansible-modules/pull/986

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.27
  config file = /home/ERADICATED/.ansible.cfg
  configured module search path = [u'/home/ERADICATED/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### COLLECTION VERSION

```
$ grep version /usr/share/ansible/collections/ansible_collections/theforeman/foreman/MANIFEST.json
  "version": "3.2.0",
```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-4.1.1.42-1.el7sat.noarch
foreman-2.5.2.18-3.el7sat.noarch
```

##### STEPS TO REPRODUCE

Run any playbook using the `theforeman.foreman` inventory plugin using an account with previously sufficient permissions:
```yaml
plugin: theforeman.foreman.foreman
url: https://satellite.example.com/
user: ansible-inventory
password: ERADICATED
validate_certs: true
want_params: false
```
##### EXPECTED RESULTS
Playbook should run normally without a warning.

##### ACTUAL RESULTS
The following warning is returned:
```
Failed to use Reports API, falling back to Hosts API: Error scheduling inventory report on foreman. Please check foreman logs!
```

**Comment by evgeni** [comment]
The change happend in the [3.0.0](https://github.com/theforeman/foreman-ansible-modules/blob/develop/CHANGELOG.rst#v3-0-0) release of the modules (in https://github.com/theforeman/foreman-ansible-modules/pull/1291 to be precise), as the Reports API is more performant if you have more than a couple of hosts.

While you're right, this needs to generate a report on each (uncached) inventory run, this saves you querying the API multiple times (as it returns only N hosts per requests) and the report generation is quicker than the API.

If you want the old behavior back, *without* the warning, set `use_reports_api=False` in your configuration.

**Comment by mpl241** [comment]
Thanks for the explanation and the effort you put into this project.  It's much appreciated.  Caching is probably the best way to deal with repeated calls to Forman for inventory, which is a whole other problem I'm having.  I guess it's time to see why my Ansible cache configuration is not working (again)!

-Matt

**Comment by evgeni** [comment]
There is an open issue around caching: https://github.com/theforeman/foreman-ansible-modules/issues/1246

I however did never investigate it further :(

**Comment by gardar** [comment]
FYI @mpl241 Satellite Includes the role `Ansible Tower Inventory Reader` which works for the foreman inventory user. Granted it has slightly broader permissions than you listed, but it's good to have a role that works out of the box.

@evgeni it would be good if the required permissions for the inventory plugin would be listed in the plugin documentation.
(And the same could be said for the other plugins/modules).

**Comment by dreua** [comment]
Let's assume I'd actually wanted to use the newer/better API and got the `Failed to use Reports API`-message, what are the requirements to make this work? Do I need to install/enable the ansible-plugin(s) in Foreman? Or is this just easily fixed by granting the correct permissions for the API-user?
