### ISSUE TITLE
Support for webhook

### ISSUE THREAD

**Issue by afeefghannam89** [theforeman/foreman-ansible-modules#1452]
##### SUMMARY
We are using foreman ansible modules to configure our RedHat Satellite. We find them very good and would like to have a module/role which create a webhook. 

Thanks

**Comment by moritzdietz** [comment]
:+1: We were also just looking into managing webhooks and webhook templates via the Ansible playbook. Hope to see this being a feature eventually.

**Comment by kkeane** [comment]
We are also looking to manage webhooks with Ansible.
