### ISSUE TITLE
Occasional timeout with subscription_manifest

### ISSUE THREAD

**Issue by myllynen** [theforeman/foreman-ansible-modules#1474]
I have an older test manifest which can be uploaded to Satellite and refreshed manually, however when refreshing it using Ansible the operation times out ("Timout waiting for Task e7b9fc02-2a76-4c4c-87b7-cc7c147d4da9"). The typo in the message reveals that it is coming from `plugins/module_utils/foreman_helper.py` but there doesn't seem a way to increase timeout for the task.

The timeout occurs after 5 minutes. The operation seems to continue in the background and finishes perhaps in 7 minutes. Given that this is an old test manifest it might be ok to stick with the 5 minute timeout but OTOH increasing the timeout would avoid the issue. So I'll leave it for your consideration what would be the most appropriate course of action here, if any. Thanks.

**Comment by evgeni** [comment]
You can edit it in the code tho:
https://github.com/theforeman/foreman-ansible-modules/blob/9d7eb91b84c3fdc02af446746948e978fe8f3059/plugins/modules/subscription_manifest.py#L87

**Comment by evgeni** [comment]
I think bumping that to 10 minutes is fine
