### ISSUE TITLE
smart-proxy - module doesn't exist

### ISSUE THREAD

**Issue by thomasmckay** [theforeman/foreman-ansible-modules#149]
No smart proxy module

**Comment by evgeni** [comment]
this will be fixed by #314

**Comment by cmeissner** [comment]
@evgeni The attached [PR#314](https://github.com/theforeman/foreman-ansible-modules/pull/314) is closed. Are there any ambitions to develop a smart_proxy module?

**Comment by evgeni** [comment]
Do we want a module? Yes. Do we have bandwidth to write one (based on the existing PR) not sure

**Comment by cmeissner** [comment]
I'll not promise much but I try to have a look for the code too. Is there a way to get help, if I decide to do some work on it? It's because I never do such development with apypie and you sophisticated code.

**Comment by evgeni** [comment]
Easiest? Pop up on IRC/Matrix (#theforeman-dev on freenode) during Europe day and we can chat (I'm Zhenech there).

**Comment by mdellweg** [comment]
ping me as x9c4 on #theforeman-dev.

**Comment by mdellweg** [comment]
@cmeissner Sorry, but you reminding me that this good work is lying around and me having a lonely train ride made me give it a spin. It felt like back in the times when we refactored all those modules over and over...
Expect a pr soon. If you still want to help, i encourage you to test it.

**Comment by cmeissner** [comment]
@mdellweg oh great to hear. It could have been the start of direct collaboration, but of course I am very happy to test it. Give me a ping, if I can start testing, maybe Monday morning.

**Comment by mdellweg** [comment]
@cmeissner It is ready to test.
Also there is #869 which might be an opportunity for contribution.

**Comment by cmeissner** [comment]
@mdellweg works fine. Thank you. Waiting for publishing the new version.
