### ISSUE TITLE
Add filter docs

### ISSUE THREAD

**Issue by samccann** [theforeman/foreman-ansible-modules#1492]
##### SUMMARY

ansible-core 2.14 adds 'side car docs' which gives collection owners the ability to add documentation for previously undocumentable filter and test plugins.

This requires creating yaml files in the same directory as the filter or test plugin code, one yaml file per plugin.

See https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/b64decode.yml for an example.

The following needs docs:
[cp_label filter](https://docs.ansible.com/ansible/devel/collections/theforeman/foreman/cp_label_filter.html#ansible-collections-theforeman-foreman-cp-label-filter)
##### ISSUE TYPE
 - Feature Idea

Related to https://github.com/ansible-community/community-team/issues/65

**Comment by evgeni** [comment]
Thanks!

We already have an issue for tracking this: https://github.com/theforeman/foreman-ansible-modules/issues/1391

Just didn't get to implement it yet.

**Comment by samccann** [comment]
@evgeni ok cool! I didn't look hard enuf then :-) Closing this duplicate and thanks.
