### ISSUE TITLE
product - state:present tries to create existing product

### ISSUE THREAD

**Issue by thomasmckay** [theforeman/foreman-ansible-modules#150]
When re-running a playbook using _katello_product_ it fails with validation for name and label. The existence of the product should be confirmed before trying to create it.

**Comment by akofink** [comment]
Using [this playbook](https://github.com/akofink/katello-ansible-seeds/blob/30a1d722a7ae1dec09c9881ff972d5eee501c6d9/seed.yml#L24), I ran and re-ran multiple times against Katello 3.7 RC1, and I cannot reproduce.

**Comment by thomasmckay** [comment]
My setup was calling the create in parallel twice which was causing the server to fail to detect some validations. Closing.
