### ISSUE TITLE
Repository-type "Ansible-Collection" ignores "ansible_collection_requirements"-parameter

### ISSUE THREAD

**Issue by IncredibleRichie** [theforeman/foreman-ansible-modules#1524]
I am trying to create repositories of type ansible-collection to sync with ansibly-galaxy.

The repository creation itself works.

If you want to specify the requirements.yaml field, it can be set in the module according to the documentation, but when you check the API call, it is set to "NULL" and the server gets "nil".

So somewhere in Ansible this parameter is not provided up to the point where it should be passed to the API.

##### ISSUE TYPE
 - Bug Report

##### Ansible version
ansible 2.9.27

##### KATELLO/FOREMAN VERSION
foreman 3.1.3
katello-4.3.1

**Comment by evgeni** [comment]
Can you post an example playbook for reproducing this?

**Comment by IncredibleRichie** [comment]
Sorry, the error was due to a typo
