### ISSUE TITLE
Real integration tests

### ISSUE THREAD

**Issue by sean797** [theforeman/foreman-ansible-modules#154]
Raising this to see if anyone is interested in dropping the recorded VCR tests for real integration tests.

I find having to record tests somewhat frustrating and some changes can require all or a lot of tests to be re-recorded (see https://github.com/theforeman/foreman-ansible-modules/pull/152) - this can prevent new contributions, as they cannot always record tests.

Based on that I would like to propose creating some real integration tests, we could do something similar to the container tests in forklift [1], which I imagine would be easier to set up, as @ehelms already done some of the work or (if we have some infra to create and destroy VMs?) we could get Jenkins to set up a monolithic VM.

[1] https://github.com/theforeman/foreman-infra/blob/master/puppet/modules/jenkins_job_builder/files/centos.org/pipelines/test/containers.groovy

**Comment by evgeni** [comment]
The benefit of VCR is, you don't need a running Foreman/Katello, which I think makes it easier to run tests for smaller changes. But I agree that re-recording the cassettes is a pain (the diff in #162 was +1,937 -757, just because of that).

The other benefit is speed. I don't want to install a fresh Foreman each time the tests run. But if I read the stuff Eric did, it's using a pre-built container, so that should be fine.

And after you finished that here, I'd love to steal it for @Katello/katello-client-bootstrap ;)

**Comment by sean797** [comment]
ping @mdellweg - since you set up the current tests, your input would be appreciated.

**Comment by mdellweg** [comment]
That is exactly the reason, why i thought my opinion would be biased. I like the tests as they are. I think they prevented us (sadly not entirely) from accidentally merging breaking changes. I e.g. stopped refactoring code that is not covered by those tests.
Anyway, if real (TM) integration tests (against containers or a fresh vm) are feasible, i would not block them.
But i think we should also consider real (TM) unit tests. Which involves designing tests for the modules, feeding them with json input and mocking calls to nailgun.

Starting to brainstorm:

- status quo:
  _pro_
  1. Speed (even running against an existing foreman instance is rather slow, at least where backends a
re involved.)
  2. Easy to be used (simple Playbook required)
  3. Almost Predictable (almost everything is contained in the repo)

  _con_
  1. Hard to contribute
  2. Tapes might not be reproducible in a new environment
  3. Tapes might be faked
  3. Tests do not automatically reflect foreman API changes

- end to end tests:
  _pro_
  1. Testing the real thing (no simulation)
  2. Easy to be used (simple Playbook required)
  3. No need for tapes

  _con_
  1. Depens on running foreman elsewhere
  2. Cannot be tested locally (?not sure?)
  3. Probably rather slow (fixtures need to be run every time)

- unit tests:
  _pro_
  1. Predictable (everything is contained in the repo)
  2. Testing can be done locally
  3. Tests do not depend on specific nailgun version
  4. No tapes
  5. Speed (very efficient)

  _con_
  1. Hard to write tests (mock, assert...)
  2. The content of the tapes must be programmed into the test by hand
  3. Tests can easily depend on implementation details
  4. Tests do not automatically reflect nailgun changes

Looking at this list (which is probably far from complete), i think what we have now is a compromise between the two extremes in every aspect, and i find it very hard to decide what kind of tests we should reach for.

**Comment by sean797** [comment]
Thanks, @mdellweg the list of pros and cons is actually very helpful.

Simply put, the problems I personally have with the status quo are:

- Currently, too many changes require re-recording tests, this means its just as slow to test a lot of the time as end-to-end tests. (Note, I don't rate the time it takes Travis or Jenkins to run tests as important as running them ourselves, no one reviews and merges stuff that quickly)
- It can be hard to find the right line in a large diff to add a comment when reviewing.

I suspect the container based tests wouldn't take _that long_ to run, the setup stages in https://ci.centos.org/job/foreman-forklift-containers-pr-test/ takes around 7/8 mins.

**Comment by evgeni** [comment]
As a data point, I usually don't read the diff of a cassette if the diff of the playbook looks reasonable.

**Comment by akofink** [comment]
I personally don't think recording cassettes is that big of an undertaking, assuming the contributor has manually tested their contribution against a running Foreman (yes, manually test your PRs please).

Testing code that depends on a changing API is something that we haven't figured out how to do easily. In the hammer-cli-* repos, we keep an [apipie cache json file](https://github.com/theforeman/hammer-cli-foreman/tree/master/test/data) up to date (and need to update it whenever any part of the API changes). Recorded cassettes are similar, but they need to be re-recorded not only when the API changes for that resource, but also when our interaction with the API changes, which is basically every PR; however, we don't need to regenerate cassettes for the entire API (unlike the apipie cache), just certain actions relating to the module under test.

We use VCR extensively in our projects, whenever there is an API we need to code against (i.e. pulp, candlepin, even our Katello React UI has something similar (i.e. [snapshots](https://jestjs.io/docs/en/snapshot-testing))). It's a very convenient solution to a difficult problem, as you can see. I would absolutely push back against ripping them out of FAM at this point; however, I'm all for adding more types of tests. Obviously VCR is for integration testing. I think we would warmly welcome any unit or functional tests submitted in a PR today. As pointed out by @mdellweg, any type of tests in this repo, including mocked/stubbed unit tests may/will require updates when the API/nailgun makes changes. That's just part of maintaining a test suite.

**Comment by sean797** [comment]
Closing this as I think, we have a general consensus that we are happy with the current state of our testing infra. Thanks guys.

If you feel differently please reopen or comment.
