### ISSUE TITLE
RPM missing on yum.theforeman.org

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-ansible-modules#1546]
Hi everyone

_tl;dr: yum.theforeman.org does not provide FAM 3.8 as RPM_

I cannot find the latest released FAM package on yum.theforeman.org:

* http://yum.theforeman.org/plugins/3.5/el8/x86_64/ contains `ansible-collection-theforeman-foreman-3.7.0-2.el8.noarch.rpm`
* http://yum.theforeman.org/plugins/latest/el8/x86_64/ contains `ansible-collection-theforeman-foreman-3.5.0-2.el8.noarch.rpm` and 3.4
* http://yum.theforeman.org/plugins/nightly/el8/x86_64/ contains `ansible-collection-theforeman-foreman-3.7.0-2.el8.noarch.rpm`

On https://galaxy.ansible.com/theforeman/foreman: 3.8.0

**Comment by maximiliankolb** [comment]
PR against foreman-packaging: https://github.com/theforeman/foreman-packaging/pull/8869

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-packaging/pull/8862 has been open for a while already

**Comment by maximiliankolb** [comment]
Thanks Evgeni!
