### ISSUE TITLE
Setup Foreman with ElasticSearch

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-ansible-modules#156]
Hey,

I am working on a document which will setup Foreman to export data to ElasticSearch/Kibana. Couple of config files are needed for that - I was thinking doing an Ansible module. Is this the right repo?

**Comment by sean797** [comment]
To answer your question - Yes! But I would also ask [Should you use a role instead?](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules.html#should-you-develop-a-module)
I assume it involves configuring a bunch of different services? If so, I would say it probably should be done via `foreman-installer` if you want to use Ansible to poke `foreman-installer` there are a couple of different roles, I'd suggest https://galaxy.ansible.com/sean797/foreman_installer ;)

**Comment by lzap** [comment]
Thanks!
