### ISSUE TITLE
theforeman.foreman.content_credential shouldn't need to specify content parameter when state=absent

### ISSUE THREAD

**Issue by bschonec** [theforeman/foreman-ansible-modules#1588]
Is it necessary to specify content: parameter when deleting (state: absent) a content credential?  IMHO, you shouldn't have to [specify the content of the credential itself](https://docs.ansible.com/ansible/latest/collections/theforeman/foreman/content_credential_module.html#parameter-content) in order to delete it.  You should just be able to delete it.

**Comment by evgeni** [comment]
Yepp, you're right. For deleting only the name should be necessary.

**Comment by evgeni** [comment]
Opened https://github.com/theforeman/foreman-ansible-modules/pull/1589 with a fix 

Thanks for reporting!
