### ISSUE TITLE
The role redhat.satellite.content_view_publish missing options from the underlying module

### ISSUE THREAD

**Issue by lucas-benedito** [theforeman/foreman-ansible-modules#1591]
##### SUMMARY
The role redhat.satellite.content_view_publish is limited to the default lifecycle_environments.
Please add the feature to provide the lifecycle_environments, force_promote and force_yum_metadata_regeneration

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
thanks for the report!

could you try the changes in https://github.com/theforeman/foreman-ansible-modules/pull/1597 whether they solve the issue for you?
