### ISSUE TITLE
Role theforeman.foreman.hostgroups shows passwords during execution when defined via root_pass

### ISSUE THREAD

**Issue by sscheib** [theforeman/foreman-ansible-modules#1699]
##### SUMMARY
Role `theforeman.foreman.hostgroups` displays root passwords defined via `root_pass` while looping over the variable `foreman_hostgroups`, e.g.:

```
changed: [host.example.com] => (item={'name': 'hg-ansible_automation_platform-rhel-8', 'parent': 'hg-base/hg-rhel-8', 'root_pass': 'my_pass_here'})
```

This **could** (partially) circumvented by applying a label to the loop:

```
  with_items:
    - "{{ foreman_hostgroups }}"
  loop_control:
    label: '{{ item.name }}'
```

This would lead to an output like so:

```
changed: [host.example.com] => (item=hg-ansible_automation_platform-rhel-8)
```

As `name` is a *mandatory* attribute, I think this is a feasible change. Of course, that will only 'fix' it if not run with verbosity (`-v+`).

Setting no_log for the playbook/task that includes the role would obviously also work, but with that the iterated items will show as `None`, which is IMHO less helpful then simply adding a `loop_label`.

I can create a PR for that, but first wanted to report the issue.
Is that something that can potentially be included into the collection or are there any drawbacks/other reasons this shouldn't be done?

##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE

1. Define list of dictionaries to pass to the role, including the option `root_pass`, e.g.:

```
foreman_hostgroups:
  - name: 'hg-ansible_automation_platform-rhel-8'
    parent: 'hg-rhel-8'
    root_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61626232643634303831343339616533633362656538323663396562303164353862653031613035
          3639373635663164656533613835646336303333323638650a643630663832636261333233613162
          33626365613834616234396335366435353533373439356132356639303132376361393133393631
          3431373139663035610a316430323732386631393830363837353235366539383137326133643364
          66656632333462326335643762303031623830373363643333336438323334396431
```
2. Run a playbook that includes the role `theforeman.foreman.hostgroups`, e.g.:

```
---
- name: 'Create host groups'
  hosts: 'all'
  gather_facts: false
  roles:
    - role: 'theforeman.foreman.hostgroups'
```

##### EXPECTED RESULTS
Password is not shown

##### ACTUAL RESULTS
```
changed: [host.example.com] => (item={'name': 'hg-ansible_automation_platform-rhel-8', 'parent': 'hg-base/hg-rhel-8', 'root_pass': 'my_pass_here'})
```

**Comment by mdellweg** [comment]
I am wondering if there really is something else we could do to fix this properly (the loop module is out of our domain and there could be a lot more places like this in ansible). I think, a value that came from a vault should always be treated like "no_log" by ansible. Maybe you can raise the issue with ansible-core too?

**Comment by evgeni** [comment]
Thanks for the detailed report!
You are right, and setting a loop label is not a good way to fix this (it would still leak to callbacks and in verbose mode), but setting no_log can also be less than helpful.

We had a similar issue in the repositories role, and ended up setting no_log dynamically in the case a secret was present:

https://github.com/theforeman/foreman-ansible-modules/blob/a98061950006a784e3699cc33d9e3da7ce9d15a6/roles/repositories/tasks/main.yml#L93

Can something similar be done here too?

As for never logging Vault things: I agree, but secrets can come from a multitude of sources and Ansible might not always know it's a "secrets" source :(

**Comment by sscheib** [comment]
@mdellweg I agree with what @evgeni said:
It's not as easy as, "if it's in the vault, mask the value", although I agree, that would be desirable.

If you take this very collection as example:
You can pass in the password to authenticate with as `foreman_password` or, if you make use of AWX or AAP, you can create a Satellite/Foreman credential, that will pass in the password as `FOREMAN_PASSWORD`.
That's not even to mention that the value of `foreman_password` could really only be a lookup to CyberArk or the like, so it only contains a password when looked up (that is also by using AWX/AAP).

@evgeni I think your proposed way is a clever solution to work around the limitations. I'll go ahead and raise a PR for that.
