### ISSUE TITLE
ansible-galaxy collection install redhat.satellite not working

### ISSUE THREAD

**Issue by darthVikes** [theforeman/foreman-ansible-modules#1716]
##### SUMMARY
ansible-galaxy collection install redhat.satellite is not working.   Seems like it was removed from Galaxy servers?   Not sure what I am not able to open an issue on that project directly.

Is there a way to get it back there, or a way to work around this issue if I download the tar.gz file?

**Comment by evgeni** [comment]
For redhat.satellite you need to get it from Automation Hub or via RPM from Red Hat, as described in https://github.com/redhatsatellite/satellite-ansible-collection

It also contains info on how to request support for it :)

**Comment by darthVikes** [comment]
Sure how it was set up was in 

./collections/requirements.yml

collections:
  - name: redhat.satellite


Will it know to get it from the Automation hub with the above?   Or can I provide it with a URL to get it to install from the Automation hub vs the Public Galaxy website?

Seems like when I do the above it fails: 

`
TASK [fetch galaxy collections from collections/requirements.(yml/yaml)] *******
failed: [localhost] (item=/var/lib/awx/projects/_19__satellite_collections/collections/requirements.yml) => {"ansible_loop_var": "item", "changed": false, "cmd": ["ansible-galaxy", "collection", "install", "-r", "/var/lib/awx/projects/_19__satellite_collections/collections/requirements.yml", "--collections-path", "/var/lib/awx/projects/.__awx_cache/_19__satellite_collections/stage/requirements_collections"], "delta": "0:00:01.386843", "end": "2024-03-06 19:31:49.050970", "item": "/var/lib/awx/projects/_19__satellite_collections/collections/requirements.yml", "msg": "non-zero return code", "rc": 1, "start": "2024-03-06 19:31:47.664127", "stderr": "[WARNING]: Skipping Galaxy server https://console.redhat.com/api/automation-\nhub/. Got an unexpected error when getting available versions of collection\nredhat.satellite: HTTP Error 400: Bad Request\nERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:\n* redhat.satellite:* (direct request)", "stderr_lines":…
`

**Comment by darthVikes** [comment]
The above was working at one point, but not sure why it is no longer working.

**Comment by evgeni** [comment]
It looks like your `ansible-galaxy` *tries* to talk to Automation Hub, but is getting an error from there. Please open a support ticket with Red Hat about this, we have no insight into Hub workings.

**Comment by darthVikes** [comment]
Ok thanks evgeni, will do.  appreciate it!
