### ISSUE TITLE
template_sync_lock setting does not accept boolean value

### ISSUE THREAD

**Issue by myllynen** [theforeman/foreman-ansible-modules#1803]
As shown in the below example, most settings can be provided as Ansible boolean but not template_sync_lock which would cause an error and so a string must be used for it instead although I think there's no reason to accept a boolean as well:

```
  - name: template_sync_force
    value: true
  - name: template_sync_lock
    value: "true"
  - name: unregister_delete_host
    value: true
```

It would be nice to be always able to use booleans for settings which can be set on or off. Thanks.

**Comment by evgeni** [comment]
It would be nice, yes. But if the setting is a string… we can't do much:

https://github.com/theforeman/foreman_templates/blob/4f84f4910e58b3b599025caa2a121f70e9bdc80b/lib/foreman_templates/engine.rb#L86-L87

**Comment by myllynen** [comment]
Oh, I see. Ok, please feel free to close this then in case there's no hope that the actual setting would change. Thanks.

**Comment by evgeni** [comment]
> Oh, I see. Ok, please feel free to close this then in case there's no hope that the actual setting would change. Thanks.

if you report an issue against foreman_templates, it might get fixed :)

**Comment by myllynen** [comment]
Uh, well, I should have investigated the issue in more detail before reporting, checking the Web UI now shows there are four different options allowed for the setting and true or false are not part of them so the example config used here was incorrect.

Sorry for the noise, it looks like all good here - unless you think the incorrect true/false should have been rejected? Ideally perhaps yes but I'm not sure would it be worth it. I'll leave it up to you to decide, please either close this or perhaps adjust the title and one day add validation. Or would you prefer me filing a generic RFE about input validation in case you think there might be other cases as well? Thanks.

**Comment by evgeni** [comment]
After talking to @ofedoren about this: how did you end up using `true` here? 

https://github.com/theforeman/foreman_templates/blob/master/lib/foreman_templates.rb#L13
suggests the values should be `lock`, `unlock`, `keep` and `keep_lock_new`?

**Comment by evgeni** [comment]
hah, mid-air collision (I miss bugzilla!)
