### ISSUE TITLE
Can we release this as a role, exactly the same as it is right now.

### ISSUE THREAD

**Issue by ericsysmin** [theforeman/foreman-ansible-modules#183]
##### SUMMARY
Can we have this released as a role, it will work and will allow us to easily test and download without advanced steps.

##### ISSUE TYPE
 - Feature Idea

**Comment by ericsysmin** [comment]
Correction, modules folder needs to get renamed to library for this to work. Module_utils can stay the same.

**Comment by mdellweg** [comment]
Not a bad idea!
Maybe a symlink from modules to library (or the other way around) is enough without breaking anything already here.

**Comment by ericsysmin** [comment]
Yep, that's how we at Avi Networks did ours which allowed easy deployment for customers to have latest and greatest code and not always have to wait for Ansible releases for patches to released code.

**Comment by ericsysmin** [comment]
@mdellweg https://github.com/theforeman/foreman-ansible-modules/pull/184
