### ISSUE TITLE
VCR tapes need re-recording for Ansible 2.7+

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#190]
##### SUMMARY
It seems that something (yay) changed in Ansible 2.7, which makes all our VCR tapes fail. See #188. Re-recording the tapes seems to help, but this will make them incompatible with Ansible 2.6 and older.

I *guess* something was monkey-patching `requests` before 2.7, and now that has been removed and here we are.

##### ISSUE TYPE
 - Bug Report

**Comment by evgeni** [comment]
@mdellweg @sean797 @akofink @ehelms thoughts on this?

I think I'd re-record the tapes and add a dependency on ansible 2.7+?

**Comment by evgeni** [comment]
@mdellweg if we add `ansible>=2.7` to `requirements-dev.txt` only, the rest will still work with an older Ansible, and we never really tested against multiple Ansible versions anyways.

**Comment by mdellweg** [comment]
That is why i am ok with it. We could add a note that older versions are no longer being tested.

**Comment by evgeni** [comment]
fixed in 39ee256
