### ISSUE TITLE
Update "version" added before we go upstream

### ISSUE THREAD

**Issue by Fobhep** [theforeman/foreman-ansible-modules#197]
Before we go upstream for the first time, we need to update/correct the "version added" parameter in the in-line YAML documentation

**Comment by sean797** [comment]
What do we want to do with this parameter once we have an Ansible Collection uploaded to galaxy? I'd suggest either dropping it (as I don't really think the value it provides is worth the effort) or using it for the Collection version..

Any opinions, @evgeni @mdellweg..

**Comment by mdellweg** [comment]
Just drop it.
