### ISSUE TITLE
Add compute_attributes support

### ISSUE THREAD

**Issue by bagasse** [theforeman/foreman-ansible-modules#222]
##### SUMMARY

Today `foreman-ansible-modules` supports:
* `compute_resource`
* `compute_profile`
But missing `compute_attribute` for a real end-to-end setup via ansible. The goal here is to setup compute_{resources, profiles, attributes} that make compute_{resources, profiles} (without the needs to use foreman API/CLI/Webui) fully usable out of the box for our foreman users. As we have multiple foreman instances, it will be easier to share common configuration parts (eg: We use mostly oVirt as compute backend and we map compute profiles to ovirt instance type. Instance types and compute profiles are identical across our foreman instances, and today it is a pain point to configure and maintain these parts of configs on all envs).

As I try to add support for compute_attributes, I saw that there is some missing parts of course in `forman-ansible-modules` but also in `nailgun` and `foreman`. I saw in foreman API doc that compute_attributes support only create/update verbs (but no list, read, delete) and I think this will be a problem.

Any pointers to achieve this are welcome :)

**Comment by sean797** [comment]
I'm not greatly familiar with Compute Resources within Foreman, much less the compute_resource API, so I may be wrong but by the looks of things `compute_attributes` are returned as put of 
- `compute_resources` https://github.com/theforeman/foreman/blob/develop/app/views/api/v2/compute_resources/show.json.rabl#L9 
- `compute_profile` https://github.com/theforeman/foreman/blob/develop/app/views/api/v2/compute_profiles/show.json.rabl#L5

---

So perhaps it would make sense to make the `resource` and `profile` modules take a `compute_attribute` option? It probably going to require Nailgun changes, I imagine it could work in a simlar same way that Activation keys can add subscriptions https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entities.py#L307. It may be best to raise it with the SatelliteQE guys

**Comment by bagasse** [comment]
@sean797, thanks for sharing. Yes I think the better way is to handle this like you said. IMHO, it make sense to add it as 'childs' of compute profile (like it is in handled foreman WebUI). I will open an issue with SatelliteQE guys to see what they think about this.
