### ISSUE TITLE
Add FAM to plugin list in foreman manual

### ISSUE THREAD

**Issue by Fobhep** [theforeman/foreman-ansible-modules#266]
I think this list here should mention our beloved FAMs ;)

https://projects.theforeman.org/projects/foreman/wiki/List_of_Plugins

**Comment by mdellweg** [comment]
It is a wiki, so i think go forth and add it. ;)

**Comment by sean797** [comment]
Added, https://projects.theforeman.org/projects/foreman/wiki/List_of_Plugins/diff?utf8=%E2%9C%93&version=158&version_from=157&commit=View+differences
