### ISSUE TITLE
Should we delete the Apypie cache in every test?

### ISSUE THREAD

**Issue by mdellweg** [theforeman/foreman-ansible-modules#280]
Apypie modules use a cached version of the servers api specification.
This can have some unforseen sideeffects with the recorded tests. Atm, at playback the first run test will provide this specification, and all subsequent tests will use it.
Maybe we should delete that cache file at the start of every test playbook to force it beeing downloaded again. That way, the test playback will be feed the matching api definition of its own fixtures.

**Comment by evgeni** [comment]
Does #292 fix this?

**Comment by mdellweg** [comment]
Trying to find it in a new temporary directory is even better. ;)
