### ISSUE TITLE
modules pretend to support check_mode while they do not

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#29]
The following modules currently announce support for check_mode:
* foreman_global_parameter
* foreman_organization
* foreman_provisioning_template
* foreman_ptable
* katello_activation_key
* katello_content_view
* katello_product
* katello_publish
* katello_repository
* katello_sync
* katello_sync_plan
* katello_upload

At least these do not and just changed stuff for me during `--check`:
* foreman_provisioning_template
* foreman_ptable

I would ask all plugin maintainers to verify their plugins and either remove `supports_check_mode=True` or (even better) add support for check_mode.

**Comment by evgeni** [comment]
@Fobhep @mdellweg @theforeman/ansible-modules

**Comment by mdellweg** [comment]
Update:
* foreman_global_parameter
* foreman_provisioning_template
* foreman_ptable
do no longer anounce this.
#36 reintroduces their check_mode with actually implementing it.

**Comment by evgeni** [comment]
With #36 merged, this leaves us with:

* foreman_organization
* katello_activation_key
* katello_content_view
* katello_product
* katello_publish
* katello_repository
* katello_sync
* katello_sync_plan
* katello_upload

Which don't use the cement glue at the moment.

**Comment by akofink** [comment]
I opened a new issue to address modules that should be using cement. https://github.com/theforeman/foreman-ansible-modules/issues/37

**Comment by mdellweg** [comment]
Can anyone ( @evgeni  / @akofink ) verify, that #41 solves this?
If we still missed a module, please update the lists accordingly.

**Comment by evgeni** [comment]
yupp, looking. thanks for the heads up

**Comment by evgeni** [comment]
I think you are right, and all modules now support check_mode (or don't pretend to).

I even found one, that said it would not support it, but actually did: https://github.com/theforeman/foreman-ansible-modules/pull/52

**Comment by evgeni** [comment]
and with that merge, nothing pretends to do or not to do anything, and I can close this :))
