### ISSUE TITLE
default to supports_check_mode=True

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#319]
##### SUMMARY
Due to the wrapper classes we have for talking to the API, all our modules support check mode at no cost. Yet they all have to define that on their own. Let's move that definition into the base class!

##### ISSUE TYPE
 - Feature Idea

**Comment by mdellweg** [comment]
The moment they implement actions (like publish, revert, promote) on their own, they need to handle the checkmode think for those explicitly. Do we want them to force supporting check_mode, or do we give them the possibility to opt out?

**Comment by evgeni** [comment]
We surely should give them the option to opt out. I just think the default value for `supports_check_mode` should be True.
