### ISSUE TITLE
standardize verify_ssl default value

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#32]
currently we have plugins that default to false, but also some default to true.

default false:
* foreman_organization.py
* katello_activation_key.py
* katello_content_view.py
* katello_lifecycle_environment.py
* katello_manifest.py
* katello_product.py
* katello_publish.py
* katello_repository.py
* katello_repository_set.py
* katello_sync.py
* katello_sync_plan.py
* katello_upload.py

default true:
* foreman_global_parameter.py
* foreman_provisioning_template.py
* foreman_ptable.py

I'd say we should default to true and allow the user to override that.

**Comment by Fobhep** [comment]
LGTM!

**Comment by mdellweg** [comment]
+1

**Comment by mdellweg** [comment]
I think, this is solved too by #41.

**Comment by evgeni** [comment]
almost. https://github.com/theforeman/foreman-ansible-modules/pull/51 is the last one. this was not done in #41.
