### ISSUE TITLE
There is a convention for importing libraries, we should conform to.

### ISSUE THREAD

**Issue by mdellweg** [theforeman/foreman-ansible-modules#326]
We should conform with:
https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_best_practices.html#importing-and-using-shared-code

**Comment by evgeni** [comment]
FWIW, this convention also requires Ansible 2.8 or newer, which we might not want to force just yet.

**Comment by mdellweg** [comment]
OK, I think, this PR can wait a little while.
