### ISSUE TITLE
collections support tracker

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#363]
This is a tracker issue for "all things collections" that are external to us AKA Evgeni's braindump:

* collections require a different import path to import from `module_utils`, see https://github.com/ansible/ansible/pull/58896
  * and you can't do `try/except` :/
* collections require a different import path for documentation fragments, see https://github.com/ansible/ansible/issues/59226
* ansible-galaxy collection build includes unrelated files into the result, see https://github.com/ansible/ansible/issues/59228
* hard to write module_utils that work both inside and outside a collection https://github.com/ansible/ansible/issues/59384
* Support running ansible-test on collections outside a collection root https://github.com/ansible/ansible/issues/60215

**Comment by evgeni** [comment]
With #438 merged, we have working workarounds for all of the above, so I think I'd close this one.

Opinions?

**Comment by mdellweg** [comment]
Is it hard to build a shipable RPM from the collection?

**Comment by evgeni** [comment]
No: https://copr.fedorainfracloud.org/coprs/evgeni/foreman-ansible-modules/

(The rpm spec uses the same hacks I added in #438, didn't migrate it to just "make dist" yet)

**Comment by mdellweg** [comment]
> (The rpm spec uses the same hacks I added in #438, didn't migrate it to just "make dist" yet)

Also `make dist` requires an unreleased version of ansible, atm.

**Comment by evgeni** [comment]
Yeah, but only the "generate tarball" step, which is not required inside the rpm anyways.

**Comment by evgeni** [comment]
closing
