### ISSUE TITLE
Make OperatingSystem handling consistent across all modules

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#373]
Maybe out of scope for this PR, but in other places we use `title ~ STRING` when searching for OSes:
https://github.com/theforeman/foreman-ansible-modules/blob/61fb6c25cfb894a03290192fbd638490b3c8cdae/plugins/modules/foreman_installation_medium.py#L144-L145

https://github.com/theforeman/foreman-ansible-modules/blob/61fb6c25cfb894a03290192fbd638490b3c8cdae/plugins/modules/foreman_architecture.py#L103-L104

While `find_resource_by_title` uses `=`:
https://github.com/theforeman/foreman-ansible-modules/blob/61fb6c25cfb894a03290192fbd638490b3c8cdae/plugins/module_utils/foreman_helper.py#L186-L188

I think the idea behind this was to make the OS search a bit fuzzier, as OS names/titles are weird.

Given you didn't write this code in the first place in this PR, I don't think we need a decision/solution here now, but I wanted to raise awareness for this.

Maybe also @mdellweg can chime in.

_Originally posted by @evgeni in https://github.com/theforeman/foreman-ansible-modules/pull/366#discussion_r306633638_

**Comment by evgeni** [comment]
please also see the full linked discussion in #366

**Comment by mdellweg** [comment]
I think it should suffice to add a `fuzzy` parameter to the `find_by` methods to replace the search string template. No need for a find_operatingsystem.

**Comment by m-bucher** [comment]
IMHO, there are two possible ways:

1. Add an additional `bool`-parameter to the concerned modules that switches between fuzzy and exact match

1. Use fuzzy search per default, but in case multiple results come back, try to do an exact match among them

Otherwise, it would never be possible to solve the following use-case (which recently came up here):

OperatingSystems:
- `Suse Linux Enterprise Server 15`
- `Suse Linux Enterprise Server 15 SP1`

Call foreman-ansible-module for `Suse Linux Enterprise Server 15` will always fail with:
```
"No unique Operating System found with title Suse Linux Enterprise Server 15"
```

**Comment by m-bucher** [comment]
In fact in the above example, if you try to create `Suse Linux Enterprise Server 15`, with the `SP1` version already existing, foreman-ansible-modules will overwrite the existing `Suse Linux Enterprise Server 15` operating system.

**Comment by mdellweg** [comment]
That is a valid point. I think, in the operatingsystem module we have to be more strict in the lookup. In every other module, we can do a best efford approach like _use the match with the shortest title_.

**Comment by mdellweg** [comment]
I think, that in contrast to the nailgun version, the operatingsystem module already tries an exact match on the description before falling back to name, version.
@m-bucher can you verify, that this solves the `...Server {,SP1}` problem on creation?

**Comment by evgeni** [comment]
I must admit that the whole way how we handle this in the `operatingsystem` module today is pretty weird and we probably should also fix that while we're at it.

We allow the user to enter the following (identifying) information: name, description, major, minor. But then, when looking for the actual entity, we use this data pretty confusingly:

https://github.com/theforeman/foreman-ansible-modules/blob/827eb5a8629c41a7e70311e08ff1ea967b258433/plugins/modules/foreman_operating_system.py#L229-L235

Turns out we match `description` to `title`, even tho there is a `description` field in Foreman. And if the user didn't pass the `description` (I never would, seems rather optional?!), we match anything from the name, major, minor list.

I think the most correct way to fix this would to use the `description` for what it is, the description. Add a new `title` field and require the user to enter either `title` or `(name, major[, minor])`. If the user enters the `title`, we can compute the others like this:

```python
(name, _, version) = title.partition(' ')
if version:
  (major, _, minor) = version.partition('.')
  if not minor:
    minor = None
else:
  major = minor = None
```

**Comment by mdellweg** [comment]
I agree on the search by description. I would however not try to parse the title, because it can be equal to the description or `<name> <major>.<minor>`. And the description could also look like it was made from a different version.

**Comment by evgeni** [comment]
I don't think you can change the `title` field via the API and it's always generated as `<name> <major>.<minor>` (well, or a subset of that).

**Comment by mdellweg** [comment]
``` json
{
            "created_at": "2019-07-31 00:05:53 UTC",
            "description": "TestOS1 SP1",
            "family": "Debian",
            "id": 36,
            "major": "1",
            "minor": "1",
            "name": "TestOS1",
            "password_hash": "SHA256",
            "release_name": "reverse whip",
            "title": "TestOS1 SP1",
            "updated_at": "2019-07-31 00:05:53 UTC"
}
```
Or it's the description.

**Comment by evgeni** [comment]
So I don't have a SLES SPsomething OS, but I have RHEL Atomic, that gets the following entry:

```yaml
name: RedHat_Enterprise_Linux_Atomic_Host
title: RedHat_Enterprise_Linux_Atomic_Host 7.2
description:Red Hat Enterprise Linux Atomic Host 7.2
major: "7"
minor: "2"
family: Redha
release_name: null
```

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman/blob/ab97a00f1924a2505a18a94fb7bfbf9af333886a/app/models/operatingsystem.rb#L143-L146

Oooooooh. Fuck.

**Comment by evgeni** [comment]
Right, then no parsing the title. Ever.

**Comment by mdellweg** [comment]
That does not explain the title in your example, where there _is_ a description.

**Comment by evgeni** [comment]
Well, thanks katello: https://github.com/Katello/katello/blob/c898619b106624a6a9682cc5e579074b4f954a79/app/models/katello/concerns/operatingsystem_extensions.rb#L38-L42

**Comment by mdellweg** [comment]
> Foreman executes `set_title` in `before_validation`, but then Katello overrides `description` in `before_creation`, which is later, so `title` is already set. :boom:

:see_no_evil: -patching :checkered_flag:

**Comment by evgeni** [comment]
Right. But coming back to my original "we handle operatingsystems wrong" issue, I think we should do the following:

For the `operatingsystem` module, we should allow the input of name, title, description, major, minor, with either name&major or title being required (technically, description is unique, so we also could allow that as the single input).
And then for searching we'd go:
1. title entered? find by title (exact match)
2. description entered? find by description (exact match)
3. find by name+major (and minor if entered), error out if more than one found (because no minor entered)
I do wonder if we should try all three if the user has entered *everything* or shortcut after 1 and 2 if nothing is found and pretend "the user has entered a unique key, we didn't find it, so let's create it".

For all modules that *reference* an operating system, I think we should search the OS as:
1. `title=user_input`
2. `title~user_input` (error out if more than one found)

yay/nay?

**Comment by mdellweg** [comment]
Yay to the second one. (Which is really a separate issue.)

I would really like not to touch the title at all in the operatingsystem module, because that is nothing we can controll in a direct manner. So if we need to create an os with only the title provided, there'd be a lot of guesswork involved. So i would start at 2. there

**Comment by evgeni** [comment]
> Yay to the second one. (Which is really a separate issue.)

It's the original issue of this issue ;)

> I would really like not to touch the title at all in the operatingsystem module, because that is nothing we can controll in a direct manner. So if we need to create an os with only the title provided, there'd be a lot of guesswork involved. So i would start at 2. there

I can see the problem now, thank you. Yes, then starting at 2 sounds reasonable, I'll edit the above comment to reflect that.
