### ISSUE TITLE
Cannot set download policy on all repositories across all organizations

### ISSUE THREAD

**Issue by jwbernin** [theforeman/foreman-ansible-modules#379]
##### SUMMARY

I have a Satellite with multiple Organizations defined. I wish to set the download policy of all repositories to 'immediate'. Normally, I would use 'foreman_search_facts' to get a list of all repositories, then use 'katello_repository' on each repository to set the download policy. However, 'katello_repository' requires an Organization parameter, and 'foreman_search_facts' does not provide an Organization owner for the repositories it returns. 

Ideally, the 'foreman_search_facts' module would include the Organization that 'owns' the repository inside each of the items in 'resources'.

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
In https://github.com/theforeman/foreman-ansible-modules/pull/412 we added details support to search facts, does that help?

Otherwise you could do it in two steps: get all orgs, get the repos for each org, update the policy.

**Comment by jwbernin** [comment]
The "full_details" on search gets me what I need. Closing this issue.
