### ISSUE TITLE
Use `required_by` from Ansible 2.8

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#399]
##### SUMMARY
Ansible 2.8 introduced a new helper called `required_by` (see https://github.com/ansible/ansible/pull/28662) which can be used to say "if the user passed optional param A, they also need to pass B and C".

I think this is a valuable extension to have.

Not sure we want to bump our minimum Ansible version to 2.8 though.

##### ISSUE TYPE
 - Feature Idea

**Comment by sean797** [comment]
just a note of something where we could use this (whenever we decided to do it)
`katello_repository_set` name & product

**Comment by mdellweg** [comment]
Just a reminder: #328 also depends on bumping the ansible dependency.

**Comment by evgeni** [comment]
"waiting on ansible not to support 2.7 anymore"

**Comment by evgeni** [comment]
So, we dropped 2.7 support now, but I can't find any place where `required_by` would be useful.

@sean797 I think your comment was before we re-did the login in `repository_set`
