### ISSUE TITLE
make the entity_spec work for non-entity modules

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#404]
##### SUMMARY

See https://github.com/theforeman/foreman-ansible-modules/pull/335#discussion_r312357992

TL;DR: entity_spec is currently coupled to the fact that it describes an "entity", while we have action modules that don't operate on an entity as such, but would still benefit from the conversion done in the spec. maybe we should call it foreman_spec?

##### ISSUE TYPE
 - Feature Idea

**Comment by mdellweg** [comment]
...foreman_spec and move it's logic to the base Class.

**Comment by evgeni** [comment]
triage: let's see where the entity_spec is used outside of entity modules and see how this can be streamlined

**Comment by mdellweg** [comment]
In the meantime the benefits also include related entity lookup.

**Comment by nesanton** [comment]
```bash
$ grep -rP 'module = (Foreman|Katello)AnsibleModule' .
./plugins/modules/foreman_template_sync.py:    module = ForemanAnsibleModule(
./plugins/modules/katello_content_view_filter.py:    module = KatelloAnsibleModule(
./plugins/modules/katello_sync.py:    module = KatelloAnsibleModule(
./plugins/modules/katello_upload.py:    module = KatelloAnsibleModule(
./plugins/modules/foreman_search_facts.py:    module = ForemanAnsibleModule(
./plugins/modules/foreman_scc_product.py:    module = KatelloAnsibleModule(
```

**Comment by nesanton** [comment]
also, issue #404 is not found
