### ISSUE TITLE
katello_upload should support more than file, rpm and deb

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#408]
deb ♥ at least 

_Originally posted by @evgeni in https://github.com/theforeman/foreman-ansible-modules/pull/403_

**Comment by evgeni** [comment]
@mdellweg implemented deb in #510

**Comment by evgeni** [comment]
this means we're missing: docker, ostree and puppet now. I find docker and ostree not *hugely* important, but puppet would be quite nice.

**Comment by itcultus** [comment]
You also miss file.
And docker is important. Apart from the current project that utilizes docker images, I have old customers asking for this. Currently,  I use hammer for those types

**Comment by evgeni** [comment]
file is supported by the module

**Comment by itcultus** [comment]
Correct, please  disregard the file comment

**Comment by evgeni** [comment]
@bagasse will see if he has time to look into this

and @evgeni will split the issue into one issue per missing type

**Comment by evgeni** [comment]
@bagasse @itcultus I've split this issue into individual ones for the different content types. please subscribe there as appropriate. I'll close this one.
