### ISSUE TITLE
katello modules should wait for finished tasks

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#423]
##### SUMMARY
many katello entities/actions take a while to create/destroy and return a foreman task when doing so. we should wait for these actions to actually complete before continuing

example issue:
when destroying a katello_repository and a foreman_organization in a row, the org destroy often fails because it's locked to the repo

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### KATELLO/FOREMAN VERSION

```

```

##### NAILGUN VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by mdellweg** [comment]
Sadly, the api-doc information does not include the information whether it is an asyncrounous request. But i would still go for detecting a task based on some heuristics, and add a `nonblocking` option for modules to decide to handle the tasks on their own.

**Comment by evgeni** [comment]
in #405 I implemented the exact opposite: a `synchronous` flag that is `False` by default and modules can opt-in to use that. Your detection is still present, so it shouldn't hurt to enable that on requests that don't return tasks.

**Comment by mdellweg** [comment]
Thanks for keeping my detection code. ;)
I'd still say defaulting to waiting a little while for tasks is probably not hurting anyone, while fulfilling the expectation that the deed is done, when the module exists. So i'd make is synchrounous by default.
It should also be more future proof if someone turns a given request into using a foreman_task.

**Comment by evgeni** [comment]
this has been implemented as part of #405
