### ISSUE TITLE
add support for diff output

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#444]
The modules currently don't support ansible's `--diff` mode that outputs a diff what has changed. It'd be cool it they did. And we should have most of the information available already.

**Comment by mdellweg** [comment]
Maybe should make this one a milestone.

**Comment by evgeni** [comment]
Technically yes, on the other side the code changes should be minimal.

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-ansible-modules/milestone/3

**Comment by evgeni** [comment]
#487 added basic diff output for many modules, but not for:

* foreman_compute_profile
* foreman_installation_medium
* foreman_job_template
* foreman_provisioning_template
* foreman_ptable
* katello_activation_key
* katello_content_view
* katello_content_view_filter

as these use `ensure_entity` multiple times. we could add explicit `save` params to `find_resource` and `ensure_entity`, thus making this less magic in such cases.

also we should add tests

**Comment by evgeni** [comment]
we now implemented everything for a basic diff support in *all* modules, closing
