### ISSUE TITLE
handle_no_nailgun cannot be in cement

### ISSUE THREAD

**Issue by mdellweg** [theforeman/foreman-ansible-modules#47]
The function handle_no_nailgun, which shall report import errors with nailgun is unavailable in case, nailgun cannot be imported, because cement uses nailgun components itself.
This must be bootstrapped another way.

**Comment by akofink** [comment]
So, one easy solution is to add a new package (i.e. `helpers.py`) that contains this function as well as any others that don't depend on nailgun.

**Comment by mdellweg** [comment]
How many are we talking about.

**Comment by akofink** [comment]
Well, just the one at the moment. I don't think we will have too many in the long term.

**Comment by mdellweg** [comment]
Hrrmpf but i like DRY. It is nothing that will be generic enough to be shifted to ansible core, right?
ACK

**Comment by akofink** [comment]
Also, it was just a brainstorm. I'm definitely open to better ideas. :wink:

**Comment by mdellweg** [comment]
Well by now we have a directory to contain one file why not have two...
Do not have a better idea though.
