### ISSUE TITLE
Should the foreman_hostgroup module be foreman_host_group?

### ISSUE THREAD

**Issue by sean797** [theforeman/foreman-ansible-modules#475]
##### SUMMARY
Does `foreman_hostgroup` fit in with the other modules? All of which have an underscore between words

The API uses `hostgroup` https://github.com/theforeman/foreman/blob/ae96cb70130968bdcc8b7a9a9af7edc7c6e0d9a8/config/routes/api/v2.rb#L142

The UI says `Host Group`:

![image](https://user-images.githubusercontent.com/13135483/64977423-44652f80-d8ab-11e9-93ef-96056a156d51.png)

Or maybe it doesn't matter that we are slightly inconsistent?

**Comment by evgeni** [comment]
Operatingsystem had an underscore and we got rid of it.

I think we've been following the API names as much as possible, so I'd vote for keeping it hostgroup.

**Comment by evgeni** [comment]
@sean797 any objections on closing this after 2 weeks?

**Comment by sean797** [comment]
:+1:
