### ISSUE TITLE
managing usergroups and external LDAP groups

### ISSUE THREAD

**Issue by olszakl** [theforeman/foreman-ansible-modules#481]
##### SUMMARY
There are no modules for managing usergroups and external auth source groups. It would be good to close this gap so whole setup can be done using playbooks only.

##### ISSUE TYPE
 - Feature Idea

**Comment by Fodoj** [comment]
usergroups are already there, this one adds external usergroups: https://github.com/theforeman/foreman-ansible-modules/pull/538

**Comment by evgeni** [comment]
I think so, yes. Closing.

@olszakl feel free to re-open or create a new one if the recently added functionality is not sufficient for your usecase.

**Comment by olszakl** [comment]
I am fine. Thanks guys.
