### ISSUE TITLE
foreman_hostgroup does not have activation_key field

### ISSUE THREAD

**Issue by wzzrd** [theforeman/foreman-ansible-modules#482]
##### SUMMARY
In order to fully define hostgroups, it's required to assign (an) activation key(s) to the hostgroup. The modules currently seem to miss this feature

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.8.4
  config file = /home/mburgerh/work/satellite/manage-satellite/ansible.cfg
  configured module search path = ['/home/mburgerh/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]

```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.10.0.55-1.el7sat.noarch
foreman-1.20.1.35-1.el7sat.noarch

```

##### APYPIE VERSION

```
Version: 0.1.0

```

**Comment by mdellweg** [comment]
See: https://github.com/theforeman/foreman-ansible-modules/issues/374#issuecomment-520428493
You can use the `parameters` to set `kt_activation_key`.

**Comment by sean797** [comment]
Is it worth adding an example with `kt_activation_key` to https://github.com/theforeman/foreman-ansible-modules/blob/a3bab34a05b9faad873e8f2a2c2e7288e77dee24/plugins/modules/foreman_hostgroup.py#L199

**Comment by mdellweg** [comment]
Not particulary a bad idea:
https://github.com/theforeman/foreman-ansible-modules/pull/488
