### ISSUE TITLE
Ability to reliably remove a series of content view versions

### ISSUE THREAD

**Issue by wzzrd** [theforeman/foreman-ansible-modules#497]
##### SUMMARY
In order to keep my Satellite / Foreman installation clean-ish, I would like to able to remove all versions of a (C)CV, except for the latest e.g. 3 versions.

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
from triage: "last 3 versions" is something that we could do on a role level, but we probably don't have enough features in the `k_content_view_version` module to cleanly remove a CV today, so this would need fixing (or at least proper testing) before such a role can exist.

**Comment by pcfe** [comment]
I would welcome such a feature and can commit to testing (I have a CI pipeline at home that generates new versions regularly, so testing this RFE will be easy for me).

**Comment by rht-jbittner** [comment]
It would be also nice to have ability to remove any content view which does not belong to any environments.

**Comment by nesanton** [comment]
@evgeni do you know if there's an upstream bug to katello for not having "de-promote" or "delete-from-lce" API call?

**Comment by evgeni** [comment]
I think that's mostly a feature so that you can only overwrite it by another version.

There is an API to remove a CV from an LCE (https://theforeman.org/plugins/katello/3.17/api/apidoc/v2/content_views/remove_from_environment.html) that I now used in https://github.com/theforeman/foreman-ansible-modules/pull/952

**Comment by nesanton** [comment]
ah! content_views, not content_view_versions. Cool
