### ISSUE TITLE
ansible-galaxy collection install theforeman.foreman does not work

### ISSUE THREAD

**Issue by flyemsafe** [theforeman/foreman-ansible-modules#517]
##### SUMMARY
Installing the collections on RHEL 7.7 fails using Ansible 2.8.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.8.5
```

##### KATELLO/FOREMAN VERSION

```

```

##### APYPIE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml
ansible-galaxy collection install theforeman.foreman
```

##### EXPECTED RESULTS

The collection module installed.

##### ACTUAL RESULTS

```
ansible-galaxy collection install theforeman.foreman
- downloading role 'collection', owned by 
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by evgeni** [comment]
Yeah, you need a `ansible-galaxy` that knows collections, so 2.9.0rc1 or newer.

**Comment by mdellweg** [comment]
I think you can still do `mazer install collection` (or something similar).

**Comment by evgeni** [comment]
Yeah, mazer is for 2.8, with 2.9 you still can use mazer, or switch to galaxy.
Mazer was basically a playground what became "ansible-galaxy collection"

**Comment by mdellweg** [comment]
That is almost what i wanted to say. You can still use mazer to some extent _if_ you are stuck with ansible 2.8.
