### ISSUE TITLE
Remove async options from modules

### ISSUE THREAD

**Issue by mdellweg** [theforeman/foreman-ansible-modules#520]
##### SUMMARY
Ansible has features to run tasks asynchronous (and later wait for them). I think we should stop supporting that at the module level.

##### ISSUE TYPE
 - Feature Idea

**Comment by jwbernin** [comment]
As a consumer of these modules, I have to ask that async support remain at least for the katello_sync module. I have a workflow where I start repo syncs as early as possible, then continue with create lifecycle environments and content views, adding repos to content views, and only then do I "wait" for the repo syncs to complete before publishing CVs. While this saves only a few minutes at best, it does save those few minutes, and if only a single small repo is being enabled/synced, it can be very noticeable.

**Comment by mdellweg** [comment]
Can you share, how you wait for those syncs, please?

**Comment by mdellweg** [comment]
@jwbernin 
would this not cover your usecase: https://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html ?

**Comment by sean797** [comment]
We had a similar conversation in https://github.com/theforeman/foreman-ansible-modules/pull/73 when it was first implemented. I'm happy to remove this and rely on https://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html

**Comment by evgeni** [comment]
I don't use async in my playbooks, so fine for me as long as the Ansible way still works.

**Comment by evgeni** [comment]
triage: remove, add a link to the ansible docs, done :)
