### ISSUE TITLE
katello_content_view_version: add description option

### ISSUE THREAD

**Issue by nesanton** [theforeman/foreman-ansible-modules#521]
##### SUMMARY
Description field seems missing. It is used often to store information about filters that the content view had at promotion time of the version in question. 
There's no other simple way to store this info within satellite, so this filed is a must.

##### ISSUE TYPE
 - Feature Idea

**Comment by mdellweg** [comment]
Can you try, whether adding a description line in the entity_spec is sufficient?

**Comment by nesanton** [comment]
Yes, it seems so. I'll record a tape and make a PR later on
