### ISSUE TITLE
foreman_role: filters are *always* removed/added

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#534]
this will not work if you remove and add exactly the same number of (different) filters.

what is the exact reason you don't update existing filters?

_Originally posted by @evgeni in https://github.com/theforeman/foreman-ansible-modules/pull/527_

**Comment by mdellweg** [comment]
Also it seems (at least in 1.22 and 1.24) that the `resource` field on the filters is unused.
