### ISSUE TITLE
Check mode for resources with parents

### ISSUE THREAD

**Issue by Fodoj** [theforeman/foreman-ansible-modules#536]
##### SUMMARY

If I define two hostgroups: PARENT and PARENT/CHILD, both none-existent yet, then Ansible will fail in Check mode. Reason is that it will try to find PARENT hostgroup on the Foreman server and it's not there yet.

While this is expected, would be great to refactor the module in a way that this is prevented. One option would be to ignore parent attribute in Check mode. Not sure what are the other options yet, but I felt it worth bringing this topic up for the discussion at least.

##### ISSUE TYPE
 - Bug Report

**Comment by evgeni** [comment]
Yeah, this is a general issue with "dependent" resources. You'll also see similar when you have a playbook that creates a content view and an activation-key that references that content view.

I could imagine doing the following in `find_resource`:

https://github.com/theforeman/foreman-ansible-modules/blob/f4e3cd817f33e4f705babe58dd5044978e973964/plugins/module_utils/foreman_helper.py#L279

```python
        results = self.list_resource(resource, search, list_params)
        if not results and thin and self.check_mode:
            results = [{'id': 0}]
```

Checking for `thin` should only make this hack apply to referred resources, not the actual one you're modifying and thus do what you suggested.

Not sure this won't break anything else, tho.

cc @mdellweg @sean797 @bagasse @ehelms

**Comment by ehelms** [comment]
If its gated on check mode only, I should think it should be relatively "safe". The alternative might be a module level setting that gives users the control over when they want to allow this case to pass (e.g. how `command` has an `args` setting).

**Comment by Fodoj** [comment]
Only one issue I can see with skipping it on check mode is that output of check mode becomes inaccurate.

**Comment by mdellweg** [comment]
I think, this will break even more than it helps, because if you specify a dependend resource, that is not available, and the playbook (run in normal mode) would not have previously created it, it would fail in normal mode, but fail to fail in check_mode. I believe those false positive results are even worse.

**Comment by evgeni** [comment]
After discussing this during triage, we think that this behaviour is expected (it's also the same with Ansible core when you e.g. use `file` to write out a config file and then try to start a service needing this file or so).

Closing as "works as expected"
