### ISSUE TITLE
katello_repository is missing param ignore_global_proxy

### ISSUE THREAD

**Issue by bzehrfuchs** [theforeman/foreman-ansible-modules#551]
##### SUMMARY
Looking at https://theforeman.org/plugins/katello/3.13/api/apidoc/v2/repositories/create.html, we're missing the parameter _ignore_global_proxy_ when creating repositories.

Foreman/Satellite uses a global proxy configuration to sync content from the internet, there are also internal repositories which should sync to Foreman/Satellite. Since this internal repos are only reachable from the internal network and not from the proxy the ignore_global_proxy parameter is required.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### KATELLO/FOREMAN VERSION

```

```

##### APYPIE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by evgeni** [comment]
FWIW this was marked as deprecated in Katello 3.13 in favor of a more generic `http_proxy_policy`.

On the one hand I'd prefer not to add deprecated options, on the other we strive to support not only the latest Katello release here, so I'm undecided.

See https://github.com/Katello/katello/commit/579d6b4e767b1b87d57737bfe934a77b9170ef32 and https://projects.theforeman.org/issues/27199

**Comment by evgeni** [comment]
triage says we can add it and mark it directly as deprecated so that users are warned.

**Comment by tervor** [comment]
Any progress on this?
I have the need to set this for some repos I configure using this ansible modules.
