### ISSUE TITLE
Enforce/Document ansible >= 2.3

### ISSUE THREAD

**Issue by akofink** [theforeman/foreman-ansible-modules#56]
It seems ansible v. 2.2 has some issues with requiring module support code:

```sh
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Could not find imported module support code for katello_upload.  Looked for either handle_no_nailgun or foreman_helper"}
```

**Comment by mdellweg** [comment]
OK for >= 2.3.
Is it like `Require: ansible >= 2.3.0` in the Documentation variable?
Should we implement a test for this before failing to import `handle_no_nailgun`?

**Comment by akofink** [comment]
I believe so, like [this](https://github.com/ansible/ansible/blob/devel/examples/DOCUMENTATION.yml#L31).

**Comment by Fobhep** [comment]
@akofink I am currently trying to tackle that issue and I came up with a bunch of questions:

- can you confirm this being solved with v.2.3+ ?
- I did a bit of research and there are several modules in ansible that use import from module_utils   before version 2.3.
- Also did you try this with a pip-installation of ansible or package?
- Virtualenv or "native"?

**Comment by Fobhep** [comment]
Generally it seems a good idea to go not beyond a certain ansible version.
I am just wondering wether we want to connect a failure to an ansible version being below a minimum, or to a failed import of module_utils or to both

**Comment by mdellweg** [comment]
From 2.3 Release notes:
> Allow module_utils for custom modules to be placed in site-specific directories and shipped in roles

**Comment by Fobhep** [comment]
ok fair enough. I guess the older modules probabally use a shared module_utils for the whole ansible project

**Comment by akofink** [comment]
@Fobhep I believe I was using Python 2.7 native on Centos 7.4. It's been a couple months :thinking:

**Comment by evgeni** [comment]
We documented this, and 2.3 is quite old. Shall this issue be closed? I'd say so :)
