### ISSUE TITLE
foreman_subnet - add other IPAM options

### ISSUE THREAD

**Issue by chsnell** [theforeman/foreman-ansible-modules#561]
##### SUMMARY
foreman_subnet currently only appears to support the choices of DHCP or Internal DB for the ipam setting.  The GUI allows these two as well as None (which really should be the default) and Random DB (the info tool tip shows another one, EUI-64, but it's not selectable in the drop down).  It would be great if the additional options available in the GUI were also available in the module, and if the defaults matched the GUI.

##### ISSUE TYPE
 - Feature Idea

**Comment by chsnell** [comment]
Looks like PR 553 will add one of those options (None).

**Comment by evgeni** [comment]
@chsnell would `None` be sufficient or do you also need `Random DB` (what is that anyways?)

**Comment by chsnell** [comment]
None is sufficient for my uses.  I have no idea what Random DB is either, I just mentioned it for feature parity with the GUI.

**Comment by evgeni** [comment]
FWIW I did a bit of research yesterday. RandomDB is like Internal, but it suggests a random IP, not the "next" one.

And EUI64 is for generating IPv6 addresses from a MAC, so you probably didn't see it because you were creating a V4 subnet?

**Comment by evgeni** [comment]
We merged #553 so you should be good. And I've now opened https://github.com/theforeman/foreman-ansible-modules/pull/585 to add the other two modes too.
