### ISSUE TITLE
foreman_subnet: add template_proxy option

### ISSUE THREAD

**Issue by nesanton** [theforeman/foreman-ansible-modules#565]
##### SUMMARY
so we now have dns_, httpboot_, discovery_, dhcp_ and tftp_ proxies. But template_proxy is missing (template_id in API).

##### ISSUE TYPE
 - Feature Idea

**Comment by nesanton** [comment]
oh, good

**Comment by evgeni** [comment]
cc @boulet-

**Comment by evgeni** [comment]
#559 is merged
