### ISSUE TITLE
Testing fails due to missing Nailgun

### ISSUE THREAD

**Issue by Fobhep** [theforeman/foreman-ansible-modules#58]
I tried today to use the testing-module to run the module tests.
These were my steps:

1.Creating a virtualenv with python 2.7
2.Installing ansible in the virtualenv
3.Running the debug-setup.yml playbook.
4. Now trying 

```
 $ ./.tmp/ansible/hacking/test-module -m modules/katello_content_view.py -a @test/data/content-view.json
****************************************
`RAW OUTPUT 
{"msg": "Missing required nailgun module (check docs or install with: pip install nailgun)", "failed": true, "invocation": {"module_args": {"username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "name": "cv3", "repositories": [{"product": "product1", "name": "repo1"}], "server_url": "https://centos7-devel.example.com", "verify_ssl": true, "organization": "\"Default Organization\"", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"}}}
```

However running the corresponding playbook fails because the demo-server is not existing and not
because of a missing nailgun module.

```
$ ansible-playbook test/demo/activation-keys.yml 
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available

 __________________
< PLAY [localhost] >
 ------------------
 ________________________
< TASK [Gathering Facts] >
 ------------------------
ok: [localhost]
 _____________________________________________
< TASK [Create katello client activation key] >
 ---------------------------------------------
fatal: [localhost -> localhost]: FAIL
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to connect to Foreman server: HTTPSConnectionPool(host='katello.example.com', port=443): Max retries exceeded with url: /katello/api/v2/organizations (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f219c309110>: Failed to establish a new connection: [Errno -2] Name or service not known',)) "}
```

pip-freeze also tells me it is there.
Am I missing out on something?

**Comment by akofink** [comment]
Hmm... I did some testing, and it appears the katello_activation_keys module contains an issue with how it's checking `check_mode`. [Here's a PR](https://github.com/theforeman/foreman-ansible-modules/pull/59) to remedy the issue.

**Comment by akofink** [comment]
I'm running my environment in a fairly bare CentOS 7 box. The only difference to your setup is that I'm not running in a virtualenv. If you can, perhaps try running in system python.

**Comment by Fobhep** [comment]
so, yes you are right it is not due to the issue you found and fixed. Other modules, like foreman_operatingsystem also crash due to nailgun importing errors.
I am going to vacation tomorrow, but if I manage I will give it a try in system python. 
Nevertheless it would be quite convenient to have a working debugging/testing in virtualenv as well, not only due to the thing that one needs it often for python-developing.

**Comment by akofink** [comment]
I agree that this should work in any python environment with the appropriate python version, of course. If it doesn't work in virtualenv we should try to get to the bottom of it. I'll try and reproduce.

**Comment by akofink** [comment]
```sh
pip install virtualenv
virtualenv ./.env
source ./.env/bin/activate
which python # ~/foreman-ansible-modules/.env/bin/python
python -V # Python 2.7.5
ansible-playbook test/demo/content-views.yml
```
It still works with virtualenv for me. I'm not positive ansible is using the virtualenv python, though.

**Comment by Fobhep** [comment]
mmh. did you install ansible in your virtualenv?
I did a 
`pip install ansible`
to make sure everything is acutally happening inside the environment.
Thanks for your effort :)

**Comment by akofink** [comment]
So, I tried running `ansible-playbook` and debugging with the test-module after `pip install ansible` in the virtualenv, and it all worked (unfortunately). Perhaps you could give me the exact SHA checked out in `./.tmp/ansible`. Perhaps it's a change there that I don't have.

**Comment by Fobhep** [comment]
hey- took a while to reply- sorry!
Is this anyways still relevant, after your PR for the "new testing"

**Comment by Fobhep** [comment]
I will close this here, since I commented in the PR thread now on the topic of virtualenvs
