### ISSUE TITLE
sre_constants.error: nothing to repeat

### ISSUE THREAD

**Issue by jerrejkw** [theforeman/foreman-ansible-modules#599]
##### SUMMARY
Running the modules with Python 2.7.5 might fail with the error "sre_constants.error: nothing to repeat" if the Python patchlevel is too low.

This is a known bug in Python and was fixed from Python 2.7.5 patchlevel 57 onwards:
https://bugzilla.redhat.com/show_bug.cgi?id=1373363

Maybe it's worth it to mention in the README file?

I know the bug is already quite old, but the modules are also supposed to work with the old Ansible 2.3 version.

##### ISSUE TYPE
 - Bug Report

##### APYPIE VERSION
```
Version: 0.2.0
```

**Comment by sean797** [comment]
Ansible 2.3 is end of life. I'd suggest we drop support for it along with <=2.7 ?

**Comment by jerrejkw** [comment]
It would make sense. We don't have to make it incompatible with older versions on purpose, but we shouldn't waste time still supporting an old version that is already out of support.

I guess this also answers my question. The bug was already resolved a long time ago. I suppose we don't have to mention it anymore in the README.

**Comment by evgeni** [comment]
While I agree that we should look at bumping our minimal Ansible version we officially support, this issue is more around which Python is used, not which Ansible, right?

@jerrejkw was you problem with one of `foreman_job_template`, `foreman_provisioning_template`, `foreman_ptable` modules? that the only ones using `re.compile`/`re.search` if I grepped correctly.

**Comment by jerrejkw** [comment]
Hi @evgeni 

Yes, we're getting a bit off-topic. The problem is not with Ansible, but Python.

I was having trouble with `foreman_compute_profile`, but the problem actually lies in the apypie dependency. Specifically, this line of code:
https://github.com/Apipie/apypie/blob/master/apypie/example.py#L4

Upon closer inspection, I think I might know what the problem is. Not the best regexer out there, but I'll take a stab at it.

Observe:

```
*****@*****$ python example.py  
Traceback (most recent call last):  
  File "example.py", line 4, in <module>
    EXAMPLE_PARSER = re.compile(r'(\w+)\s+([^\n]*)\n?(.*)?\n(\d+)\n(.*)', re.DOTALL)
  File "/usr/lib64/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
```

This might be the sticky part: `(.*)?\n`. Should it be `(.*)\n?`? It would make a lot more sense. Python is also no longer complaining.


In retrospect, I should have submitted the issue on the apypie project. I just didn't consider it might have been a bad regex statement. :disappointed:

**Comment by evgeni** [comment]
Thanks for digging further into this!

Yes, this should have been reported against apypie, but given it's also owned by the same people, let's see if we can fix it for you ;)

**Comment by evgeni** [comment]
@jerrejkw can you try the patch I posted in https://github.com/Apipie/apypie/pull/61 in your environment?

**Comment by jerrejkw** [comment]
> @jerrejkw can you try the patch I posted in [Apipie/apypie#61](https://github.com/Apipie/apypie/pull/61) in your environment?

Works like a charm. I applied to patch to my venv and the foreman module now run without problems on older python.

Thanks for fixing it!

**Comment by evgeni** [comment]
Thanks for testing! I'll merge when someone from the apypie team tells me we're not crazy ;)
