### ISSUE TITLE
katello_product to be enriched with additional idempotency

### ISSUE THREAD

**Issue by gabriel-mh** [theforeman/foreman-ansible-modules#601]
##### SUMMARY
Module katello_product exits when product of the same name already exists.

##### ISSUE TYPE
 - Have the module check for differences between parameters passed and products current parameters and update the product with passed parameters if they differ, returning 'ok' otherwise. 

A different wording would be: Allow katello_product module to update existing products.

**Comment by mdellweg** [comment]
IIRC katello_product updates existing products, as can also be seen in the very test we run against it:
https://github.com/theforeman/foreman-ansible-modules/blob/master/tests/test_playbooks/product.yml#L36

If you see a specific parameter that is not updateable, please add that information here.
Also a sequence of <=3 tasks to show your finding would help a lot.

**Comment by evgeni** [comment]
ping @gabriel-mh, can you provide a playbook that has this issue, because we can't reproduce it here.

**Comment by gabriel-mh** [comment]
@evgeni sory for not getting to you sooner, after an environment upgrade I'll post the playbook.

**Comment by gabriel-mh** [comment]
Updating to the latest version fixed the issue.
