### ISSUE TITLE
Write an Automated Test Suite

### ISSUE THREAD

**Issue by akofink** [theforeman/foreman-ansible-modules#61]
We have `test/demo/*.yml` and `test/data/*.json` for manual testing. The goal is to create automated tests that will be run against every PR.

**Comment by akofink** [comment]
Even if we just run all the demo playbooks in a particular order (i.e. set up products before repos), it'd be a good smoke test. The main issue is that we don't have a running katello/foreman instance, and it'd be resource intensive to bring up a fresh instance every time.

Ideally, we'd be able to use an apipie cache like we do [in hammer](https://github.com/theforeman/hammer-cli-foreman/blob/master/lib/hammer_cli_foreman/testing/api_expectations.rb).

**Comment by mdellweg** [comment]
For starters, i would be satisfied, if i could run them all against my local forklift instance. It would make reviews easier. It would help if the tests for the single modules were self contained. That could mean, that a module that needs i.e. an organization `present`s one with a common name, thar can be reused by all other tests. Alternatively, we could have a `setup.yml` and a `teardown.yml` to handle these fixtures.

**Comment by Fobhep** [comment]
ideally we tailor the test to use either a pre-installed forklift or "lift-up" a new instance

**Comment by akofink** [comment]
Ok, so after a few days of thought and tinkering, I have some ideas:

1. We should create a common interface (i.e. Makefile) to setup/debug/test. I have this framework already. I can submit a PR; I don't have any tests yet, but the structure is there for python unittests.
1. It'd be great to have a way to both run against a live Katello instance (say, locally for manual testing) and a way to run against cached API structure. I found this project named [vcrpy](https://github.com/kevin1024/vcrpy/). It's a fork of a Ruby version of the same library that we use in hammer-cli-csv tests.

Thoughts?

**Comment by karras** [comment]
I could probably sponsor / organize a VM for testing purpose.
You could also make use of something like Molecule: https://github.com/metacloud/molecule

**Comment by ehelms** [comment]
Some thoughts from our experience building tests for Runcible and Katello using VCR against Pulp.

First, we could start by considering that these modules should work across multiple versions of the software, and that we want to support a specific set. Then, using vcrpy, we could create tests and recorded individual cassettes per software version. This, in theory, means we can have API copies for various versions and ensure changes match those API expectations in the future. Adding a new supported version or dropping one would mean simply dropping the cassettes for it. This would also, if we wanted, allow different modules to support different versions if we don't want to "backport" module support.

**Comment by mdellweg** [comment]
UPDATE:
After merging #62 , we now have a testsuite that runs against a local foreman/katello instance.
The individual test consists of running a specific playbook (examples for organization and product are in place). Now, they are structured like:
* Create depended on entities (fixtures)
* Run some test tasks
* Destroy the fixtures
I think, it is time, for more playbooks to be added.
An important open question remains:
Should we create the fixtures for individual tests, or should we collect them in a `setup.yml` and `teardown.yml'? That way organitzations (e.g.) can be created once and then be used by all tests.

**Comment by akofink** [comment]
Ideally, we would only create the org once, and that would count as the organization create test. Same for destroy; however, we have some complex dependencies between models (i.e. repository requires a product, host requires all kinds of stuff). If we can figure that out and have the tests run in a specific order it would be great.

We could have a single playbook that exercises all the modules exactly once, but then it'd be difficult to test just a single module. On the other hand, maybe we could have a full suite playbook as well as individual model playbooks for running locally. I'm not sure what the answer is here.

**Comment by mdellweg** [comment]
If we tagged the playbooks, we could run all 'setup' tagged tasks first. If we had more than one entity in need of an organization, they could use the same, which would be created only once (here not being a test). Then we could run the untagged tasks (aka "tests"), and if we really like to end up clean, we could run the ones tagged 'teardown'. Idempotence should save us some testing time that way.
This of course needs a proper naming scheme (e.g. `organization_fixture1` vs. organization_test1`).
Personally i give a very strong +1 to keeping individual and independent playbooks.

**Comment by mdellweg** [comment]
closed by #76
