### ISSUE TITLE
decide which workflows we want to support in our roles

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#644]
##### SUMMARY
Based on the discussion in https://github.com/theforeman/foreman-ansible-modules/issues/535, we need to decide which workflows we want to cover in our official/supported roles, and which would be out of scope.

This list does not have to be final, but having a few distinctive workflows will make bootstraping the roles easier.

**Comment by evgeni** [comment]
example roles we should look at when looking for workflows:
* https://github.com/jwbernin/sat6-config
* https://github.com/theforeman/foreman-ansible-modules/pull/548
* https://github.com/sean797/ansible-role-configure-katello/
* https://github.com/flyemsafe/satellite-day-two-ops

**Comment by willtome** [comment]
Here is an example of configuration roles that work really well (https://github.com/redhat-cop/tower_configuration)
Here is an example of using roles + variables to define configuration (https://github.com/redhat-cop/agnosticd/blob/f9801a0aa9386d0f70290fc295a65ed620f45ab1/ansible/configs/smart-management/sample_vars_patching.yml#L389)

**Comment by evgeni** [comment]
we started to have roles, mostly around content, so we'll closing this issue now
