### ISSUE TITLE
naming convention for roles

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#645]
##### SUMMARY
based on the discussion in https://github.com/theforeman/foreman-ansible-modules/issues/535, we need to decide on a naming convention for roles.

my suggestion would be `<foreman|katello>_<workflow_name>` (similar to what we do in modules), so we'd end up with things like `foreman_configure_provisioning`, `foreman_setup_vmware_cr`, `katello_configure_content`, `katello_sync_content` etc

##### ISSUE TYPE
 - Feature Idea

**Comment by ehelms** [comment]
Given we now have roles present following a naming convention, I propose we close this issue.

**Comment by evgeni** [comment]
agreed
