### ISSUE TITLE
Add  foreman_smart_class_parameter module

### ISSUE THREAD

**Issue by bagasse** [theforeman/foreman-ansible-modules#676]
##### SUMMARY

Add foreman_smart_class_parameter to add support for smart class parameters and overrides.

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
@bagasse given you assigned yourself, I guess you'll gona work on this?

**Comment by bagasse** [comment]
@evgeni, yes, this is work in progress.
