### ISSUE TITLE
Check for missing commits vs devel

### ISSUE THREAD

**Issue by gundalow** [theforeman/foreman-ansible-modules#727]
##### SUMMARY
The "Big Migration" has now taken place.

As this collection already exists, we need to carefully check to see if any further commits went into devel since this repo was created.

Please check the contents of https://github.com/ansible-collection-migration/theforeman.foreman against this repo

##### ISSUE TYPE
- Bug Report

**Comment by gundalow** [comment]
Clarification:
* Please do a per-file level diff against every file in the ansible-collection-migration repo and this one
* Pay care to files added and removed.
* During the last two weeks there have been lots of fixes, especially around and tests, dependencies, and new collection features e.g. meta/action_groups.yml

**Comment by evgeni** [comment]
I don't completely understand what the linked repo is? It contains just the callback and inventory plugins, so it's not the collection it pretends to be? ;)

**Comment by gundalow** [comment]
> I don't completely understand what the linked repo is? It contains just the callback and inventory plugins, so it's not the collection it pretends to be? ;)

Hi, forgive my copy and pasting from the initial issue.

I just want to make sure that any files in https://github.com/ansible-collection-migration/theforeman.foreman are identical to the ones included in https://github.com/theforeman/foreman-ansible-modules/

Some of the recent updates to `migrate.py` (which is used to generate https://github.com/ansible-collection-migration/theforeman.foreman) have been to fixed how Python or integration test imports are done. I want to ensure that foreman-ansible-modules isn't missing any of those fixes.

**Comment by evgeni** [comment]
Fwiw, I checked the callback, diff was empty :)
