### ISSUE TITLE
resolve_entities does not resolve the scope when entity_resolve=False

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#737]
##### SUMMARY
This came out when looking at #712 and I am not 100% sure we want to fix that or ignore the corner case.

What happened?
* images are unique per compute_resource AND operating_system
* to find the unique image you want to manipulate, you need to scope by CR and then add OS to the search (ugh)
* as this is not easily supported by resolve_entities, we used `entity_resolve=False`
* when we do that, resolve_entities also does not resolve the CR scope that we passed with `entity_scope=compute_resource`

should it tho? or should it not? I am not sure.

@bagasse I'd love your thoughts on that.

see https://github.com/theforeman/foreman-ansible-modules/blob/827acd8232c154a5f075e9d53112ba96114fa4b3/plugins/modules/foreman_image.py#L120-L125 for an example of code that maybe could be simplified, but at which cost?

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### KATELLO/FOREMAN VERSION

```

```

##### APYPIE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by bagasse** [comment]
Yes, it should resolve compute_resource, for me it's a bug. When `entity_resolve=False` is set, only the related entity should not be resolved.

**Comment by evgeni** [comment]
Thanks! I think @mdellweg has an (accidental) fix for that after we merge his last refactoring pr ;)

**Comment by mdellweg** [comment]
With automatic scope dependency resolution, this should indeed be fixed.
