### ISSUE TITLE
foreman_hostgroup module is missing documentation for puppetclasses parameter

### ISSUE THREAD

**Issue by ogajduse** [theforeman/foreman-ansible-modules#750]
##### SUMMARY

SSIA
I found out that there is not only `puppetclasses` parameter that is not mentioned in the foreman_hostgroup docstring. 

https://github.com/theforeman/foreman-ansible-modules/blob/83181d145ac70708d00471148baa3a874cf006f7/plugins/modules/foreman_hostgroup.py#L191
##### ISSUE TYPE
 - Feature Idea

**Comment by mdellweg** [comment]
It is in the shared host/hostgroup doc_fragment.
Also Errors like this ought to be identified by make sanity in the CI.

I am going to close this. Please verify the documentation by calling `ansible-doc` and reopen accordingly.

**Comment by ogajduse** [comment]
Thank you for the insight into the documentation workflow.

I use FAM after a half-year pause, so this is quite new to me.
