### ISSUE TITLE
Ability to return a list of items

### ISSUE THREAD

**Issue by pmgration** [theforeman/foreman-ansible-modules#762]
##### SUMMARY
With FAM it is currently possible to create and delete items such as domains, subnets, hosts etc but I haven't found a way to return a list of the current domains registered in a foreman instance for example.

The use case I'm looking at is maintaining an up to date foreman instance based on information from an ansible inventory (the inventory data is from a custom plugin that queries an asset register)..if any of the domains for hosts in the inventory are no longer required, how do I know which to delete without comparing with the existing list?
If deleting a domain, the domain would need to be unassigned from the subnet first, so I'd need to find out which subnets have the domain association and remove those before deleting the domain.

This may already be possible but I haven't found anything in the documentation to suggest it

##### ISSUE TYPE
 - Feature Idea

**Comment by mdellweg** [comment]
https://theforeman.org/plugins/foreman-ansible-modules/sphinx/modules/foreman_search_facts_module.html#foreman-search-facts-module

This should do.

**Comment by pmgration** [comment]
Ah, missed that, thanks!

Does the documentation need updating for some of the examples in that module?

Wondering if [this](https://github.com/theforeman/foreman-ansible-modules/blob/v0.7.0/plugins/modules/foreman_search_facts.py#L87) (and others) should now be:

```yaml
- debug:
    var: item.name
  with_items: "{{ result.resources }}"
```

**Comment by evgeni** [comment]
I had to look twice to notice you added `{{ }}` around it, but yeah, you're right, it should.

Want to open a PR?

**Comment by pmgration** [comment]
Sure, I'll aim to take a look at this soon
