### ISSUE TITLE
add module for job invocations

### ISSUE THREAD

**Issue by pondrejk** [theforeman/foreman-ansible-modules#777]
##### SUMMARY
ability to set remote execution jobs via ansible module

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
@pondrejk should we assign that to you, or would you prefer not to? :)

**Comment by pondrejk** [comment]
@evgeni np, I'm scrambling up a starter PR, the idea is to support just command and service job templates, then see how to extend

**Comment by evgeni** [comment]
closed via #864
