### ISSUE TITLE
creating an existing LCE fails

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#782]
##### SUMMARY
when you try to use `k_lifecycle_environment` with an existing LCE (so a noop operation), you get the following backtrace:

```
Traceback (most recent call last):
  File "/tmp/ansible_ZKmSAH/ansible_module_katello_lifecycle_environment.py", line 111, in <module>
    main()
  File "/tmp/ansible_ZKmSAH/ansible_module_katello_lifecycle_environment.py", line 104, in main
    if 'prior' in module.foreman_params and entity['prior']['id'] != module.foreman_params['prior']['id']:
TypeError: string indices must be integers, not str
```

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### KATELLO/FOREMAN VERSION

```

```

##### APYPIE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by evgeni** [comment]
@mdellweg I think this is due to one of your last refactorings, as `prior` seems not to be resolved yet at this point.

**Comment by mdellweg** [comment]
right. Only 'entity' is resolve upfront.

**Comment by evgeni** [comment]
IMHO not that easy (two line patch took an hour?) :)
