### ISSUE TITLE
Add SCA toggle to redhat_manifest

### ISSUE THREAD

**Issue by sean797** [theforeman/foreman-ansible-modules#820]
##### SUMMARY
Subscription Allocations in the Red Hat portal now have a "Simple Content Access" toggle, we should add support for this in the Ansible module.

##### ISSUE TYPE
 - Feature Idea

![Screenshot from 2020-05-21 07-36-12](https://user-images.githubusercontent.com/13135483/82530716-d78aef00-9b35-11ea-9677-a4d0db28f31a.png)

**Comment by evgeni** [comment]
great idea, I'm sure you can provide docs and a patch? :)

**Comment by evgeni** [comment]
Ping @sean797, do we have docs of the portal API so we can implement that feature?
