### ISSUE TITLE
Split katello_sync module

### ISSUE THREAD

**Issue by mdellweg** [theforeman/foreman-ansible-modules#83]
The discussion in #78 lead to the consensus that we want to split the `katello_sync` module into `katello_product_sync` and `katello_repository_sync` to have overall consistent naming.

Secondary goal: Use module_utils to keep the code duplication small.

**Comment by itewk** [comment]
comming from `katello` module i dont see how I can sync a product without also specifying a repository, and that is annoying

**Comment by itewk** [comment]
nevermind. doc is just wrong.

https://github.com/theforeman/foreman-ansible-modules/blob/master/modules/katello_sync.py#L51 says `repositories` is required but in reality it is not (https://github.com/theforeman/foreman-ansible-modules/blob/master/modules/katello_sync.py#L150)

**Comment by mdellweg** [comment]
Is this still a thing? I think, at least the documentation here has been improved by #241 .

**Comment by sean797** [comment]
IMO - no, I'd :-1: this

**Comment by mdellweg** [comment]
BTW: I think the secondary goal is met. :desert: :camel:

**Comment by mdellweg** [comment]
Given that there were no objections, i am going to close this one.
