### ISSUE TITLE
ansible-callback plugin should indicate type

### ISSUE THREAD

**Issue by m-bucher** [theforeman/foreman-ansible-modules#836]
##### SUMMARY
Currently foreman_ansible-module struggles to identify reports from foreman ansible-callback plugin
This needs to be fixed in sync with https://github.com/theforeman/foreman_ansible (see also https://projects.theforeman.org/issues/28069).

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### KATELLO/FOREMAN VERSION

```
tfm-rubygem-katello-3.14.1
foreman-1.24.3
```

##### APYPIE VERSION

```
Metadata-Version: 1.1
Version: 0.2.1
```

##### STEPS TO REPRODUCE

Attach an ansible role to a host and click `Run Ansible roles`
The report is not detected to come from Ansible, because foreman_ansible looks for `_ansible_parsed` within the report.

##### EXPECTED RESULTS

foreman_ansible should be able to clearly detect the report as coming from ansible.

##### ACTUAL RESULTS

foreman_ansible does not find `_ansible_parsed` in the report and therefore foreman does not indicate the Report as being from ansible (by showing the Ansible Logo in the report-overview).

**Comment by evgeni** [comment]
@m-bucher so we basically just need to port https://github.com/ansible/ansible/pull/55437/files to our codebase?

**Comment by evgeni** [comment]
Otherwise, I have no idea what needs to be done here :(

**Comment by m-bucher** [comment]
That might be enough, however we should also check if foreman can evaluate this new parameter.
@xprazak2 could you please open https://github.com/ansible/ansible/pull/55437,here?
