### ISSUE TITLE
allow for environment fallback for url/user/pass

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#837]
##### SUMMARY
Ansible supports automatic environment lookup for parameters (see https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#fallback) which I think can be useful for url/user/pass

##### ISSUE TYPE
 - Feature Idea

**Comment by ptoal** [comment]
It would help to co-ordinate with awx/tower, as well: https://github.com/ansible/awx/issues/2192
