### ISSUE TITLE
katello_sync example leads to bad performance

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#838]
##### SUMMARY
the example in `katello_sync` tells the user to search for all available repos and then trigger a sync on all of them in parallel. this can lead to a very high load on the system, especially on memory, sometimes killing MongoDB and friends, thus actually breaking the system.

I think we should not give such examples.

@sean797 you added that example in #211 -- care to weight in? :)

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### KATELLO/FOREMAN VERSION

```

```

##### APYPIE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by sean797** [comment]
Seems like a fair use case, shame we do not handle it well.

Removing it as a short term solution makes sense to me
