### ISSUE TITLE
move boilerplate code/docs to helper

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#84]
this came up during a discussion with @Fobhep and @mdellweg 

we have quite a lot of boilerplate code and docs in the modules, mostly around documenting and handling server url, username, password and ssl settings. I *think* we should move it to the helper script and just append the really module specific options in the module.

**Comment by sean797** [comment]
Shame we cannot make use of `extends_documentation_fragment` as the path it looks doesn't seem to be configurable within Ansible 👎

**Comment by evgeni** [comment]
the code part was mostly fixed in #228, and docs are waiting on ansible 2.8 in #230 

progress!

**Comment by mdellweg** [comment]
Ansible 2.8 is there.

**Comment by evgeni** [comment]
so, both PRs are done, so I'd consider this issue done too.
