### ISSUE TITLE
Inventory plugin want_params is broken

### ISSUE THREAD

**Issue by erezzarum** [theforeman/foreman-ansible-modules#847]
##### SUMMARY
When using Foreman as an inventory plugin with "want_params" set to True it seems as only few parameters are available.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
2.9
```

##### KATELLO/FOREMAN VERSION

```
2.0
```

##### STEPS TO REPRODUCE

```yaml
Use "want_params" set to True/yes
```

##### EXPECTED RESULTS

Parameters included in host inventory variables

##### ACTUAL RESULTS

```
nothing.
```

If using "legacy_hostvars" so foreman_params is available.
Looking at "plugin/inventory/foreman.py" line 264:
```
self.inventory.set_variable(host_name, p['name'], p['value'])
```
When it should be:
```
self.inventory.set_variable(host_name, k, v)
```

A small suggestion, why not use the Host "ENC" api to get the parameters?
It seems like this is a better idea, it would fetch both the parameters and smart class parameters (ansible, puppet, etc..)

**Comment by evgeni** [comment]
Thanks @erezzarum! The proposed fix is correct and I've applied it in #921.

As for the ENC API, I don't know for sure, but we have a separate issue for that topic open: #851
