### ISSUE TITLE
Add module stream filter_type to katello_content_view_filter

### ISSUE THREAD

**Issue by ich199** [theforeman/foreman-ansible-modules#854]
##### SUMMARY
From both the Katello UI and via hammer, you are able to add a content view filter rule to filter module streams from Yum content. This is not currently possible using the katello_content_view_filter module.

![screenshot_2020-06-24-10:13:08](https://user-images.githubusercontent.com/17448821/85528466-d43ac580-b603-11ea-9ef4-9d0065751c53.png)

##### ISSUE TYPE
 - Feature Idea

**Comment by nesanton** [comment]
I might take it in a week if no one does before.

**Comment by evgeni** [comment]
So I had a brief look at the API for that and I fear it's non-trivial to add right now.

The CV Filter Rule API expects a ModuleStream ID, which is just the numerical ID in the DB, so if we add a `module_streams` parameter, we'll have to do a search on the modulestream API endpoint to find the right stream id, and the API allows searching for the following terms: name, uuid, stream, version, context, arch, host, module_spec. the spec is the most verbose (it's NAME:STREAM:VERSION:CONTEXT:ARCH/PROFILE essentially) but we should allow the user to do any of these (well, maybe not host, that's IMHO not too useful in this context)

I vote we implement that when we have split the module into `content_view_filter` and `content_view_filter_rule`.

**Comment by Blackmoresknight** [comment]
It would also be nice to be able to filter out all module streams (exclude all) if possible.

**Comment by tinsjourney** [comment]
any update on the split of the module ?
Would be nice to be able to use ansible module to create a filter like "Include all Module Streams with no errata."

**Comment by RJBJongejan** [comment]
Any update on this?

**Comment by parmstro** [comment]
Please split the module into content_view_filter and content_view_filter_rule. Soonest. And implement modulemd. I need this functionality badly. You can't create content views with filters on anything with modules without this. My tests in Satellite show that you need both All RPMS no errata + All Streams no errata + your date based erratum filter or your content view is missing components and installs and patching fails. If we can at least support an include filter of type modulemd with original_packages=true that gets many content views over the hump.

**Comment by Fabian1976** [comment]
Any update on this?

**Comment by parmstro** [comment]
Not yet, my day job is getting in my way. :-)
I have started working on it.


Paul Armstrong
Principal Technical Specialist
Red Hat Technical Sales Organization
647-285-0044

**Comment by RJBJongejan** [comment]
Can you give an update on this? I would very much like to automate my rhel8/rhel9 content views with this.

**Comment by fltux** [comment]
I also really want this. My ugly workaround hack consists of 4 tasks and the module stream filters is deleted and created every time:
- lookup content view id
- lookup filter id in content view
- delete module stream filter in content view through api
- create module stream filter in content view through api

**Comment by evgeni** [comment]
done in https://github.com/theforeman/foreman-ansible-modules/pull/1558
