### ISSUE TITLE
Need a way to allow lifecycle environment synchronization to smart_proxy

### ISSUE THREAD

**Issue by dabelenda** [theforeman/foreman-ansible-modules#869]
##### SUMMARY
When creating a new LifeCycle Environement, it needs to be explicitely selected in capsules to be synchronized. However, there is no way to do it in Ansible, so each time a new LifeCycle Environment is created it needs to be manually added to the capsules in the WebUI.

Please make it so that the synchronization can be added automatically.

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
We don't a smart_proxy module yet, but as soon as we do (see https://github.com/theforeman/foreman-ansible-modules/issues/149) we can add that feature to it

**Comment by dabelenda** [comment]
The problem I see is #149 is that nobody is currently working on it (since before I opened this issue).

**Comment by evgeni** [comment]
There is now progress being made in https://github.com/theforeman/foreman-ansible-modules/pull/981!

**Comment by evgeni** [comment]
However, looking at https://theforeman.org/plugins/katello/3.16/api/apidoc/v2/smart_proxies/create.html, I don't see how one can assign an LCE there.

**Comment by evgeni** [comment]
Ooh, it's a totally different API endpoint. Yikes. https://theforeman.org/plugins/katello/3.16/api/apidoc/v2/capsule_content.html

@mdellweg do you think this should be added to the smart_proxy module or separate? It feels more natural in s_p, but ewwwww API wise.

**Comment by mdellweg** [comment]
I could see that as a list of sort of subentities in smart_proxy. Like we used to handle nested parameters.

**Comment by evgeni** [comment]
Yeah, something like that should work

**Comment by mdellweg** [comment]
But let's make that a separate PR.

**Comment by evgeni** [comment]
Absolutely

**Comment by dabelenda** [comment]
Nice, thank you for working on this.

Personnally, I would prefer to have the list of capsules where the LifeCycle environment is replicated in the LifeCycle environment definition.
I find it cleaner in the ansible code, specially if you want to define lifecycle environments in different playbooks/inventories.

**Comment by mdellweg** [comment]
> Nice, thank you for working on this.
> 
> Personnally, I would prefer to have the list of capsules where the LifeCycle environment is replicated in the LifeCycle environment definition.
> I find it cleaner in the ansible code, specially if you want to define lifecycle environments in different playbooks/inventories.

That is an interesting idea, maybe we can have both, or this is again an argument for an independent proxy_life_cycle module and a role to combine them.

**Comment by Thulium-Drake** [comment]
Given that the API is separate as well, I'd say, go with the smart_proxy_lifecycle approach, I feel that should be easier to implement and easier on the maintenance.

**Comment by Thulium-Drake** [comment]
I tried to make a module that will set the synchronized Lifecycle Environments for it. The furthest I was able to get what the following error:

```
msg: 'Failed to list resource: Exception: The server doesn''t know about capsule_contents, is the right plugin installed?'
```

Which is correct, because the API endpoint is capsule_content. But I can't find where I can fix that in module_utils/foreman_helper.py. I did find a note that it will always assume the plural name of the entity, is that where I need to look?

**Comment by evgeni** [comment]
FWIW, I think having "lifecycle_environments" as a list in the normal "smart_proxy" module is easy enough to implement and a cleaner interface than having a separate module (it's also how hammer does it).

**Comment by evgeni** [comment]
As for the error, you can set "resource_type" to override the automatic plural naming.

**Comment by Thulium-Drake** [comment]
I may have almost got it. When I hard code a environment ID to attach to the smart proxy, it works. But I need to resolve them from name to ID first. I tried looking in other modules, but ```module.lookup_entity('lifecycle_environments')``` does not work. It gives the following error:

```
msg: 'Failed to list resource: KeyError: "Unknown action ''index''. Supported actions: add_lifecycle_environment, available_lifecycle_environments, cancel_sync, lifecycle_environments, remove_lifecycle_environment, sync, sync_status"'
```

I have taken the logic from the sync_plan module and adapted it, but I might have broken some other thing in the process..

The PR is #1026

**Comment by evgeni** [comment]
#1026 is merged, closing

**Comment by dabelenda** [comment]
I am sad you did not consider my use-case as a valid one.

> Personnally, I would prefer to have the list of capsules where the LifeCycle environment is replicated in the LifeCycle environment definition.
> I find it cleaner in the ansible code, specially if you want to define lifecycle environments in different playbooks/inventories.

**Comment by mdellweg** [comment]
> I am sad you did not consider my use-case as a valid one.
> 
> > Personnally, I would prefer to have the list of capsules where the LifeCycle environment is replicated in the LifeCycle environment definition.
> > I find it cleaner in the ansible code, specially if you want to define lifecycle environments in different playbooks/inventories.

@Thulium-Drake 
Do you think this is possible on top?

**Comment by Thulium-Drake** [comment]
I think it is, it sounds like the reverse of the logic we have built in smart_proxy, we are provided with some details on the smart_proxy, look up some LCEs and bring them together.

What you are suggesting is a module where you are provided with the details on the LCE and you need to look up some smart_proxies and bring them together.

@dabelenda is the mocked up module invocation what you mean?

```
- name: 'Ensure Lifecycle Environment'
  theforeman.foreman.lifecycle_environment:
    username: "admin"
    password: "changeme"
    server_url: "https://foreman.example.com"
    name: "Production"
    label: "production"
    organization: "Default Organization"
    prior: "Library"
    description: "The production environment"
    state: "present"
    smart_proxies:
      - "foreman-proxy.example.com"
```

**Comment by evgeni** [comment]
@dabelenda could you post a fictional playbook how you'd invision that workflow? something like this?

```
- name: attach lce to proxy
  lifecycle_environment:
    name: Test
    proxies:
      - proxy01.example.com
      - proxy02.example.com
```

**Comment by dabelenda** [comment]
@evgeni @Thulium-Drake 
It could be that, or a completely separate action. The point is, I have multiple teams working independently on multiple CV/CCV/LCE so we have a single playbook that manages everything in Satellite, and splited the inventories so that everybody uses the same code, only the relevant descriptions change.

**Comment by dabelenda** [comment]
Also: We use a CICD to apply the changes in Satellite, and right now, due to the Capsules not being managed by ansible we need to use the WebUI to set the smart_proxy, then start a manual smart_proxy sync.

**Comment by evgeni** [comment]
I've opened #1039 to further track this.
