### ISSUE TITLE
tag to mark upstream-only tasks in test playbook

### ISSUE THREAD

**Issue by pondrejk** [theforeman/foreman-ansible-modules#897]
##### SUMMARY
Basically I'd welcome a way to exclude tasks that won't work downstream (debian repo tests, etc.). I suppose the solution would be to have an 'upstream_only'  tag + a way to tell 'make record_' to pass down the --skip-tags option.

Different suggestions are welcome :)

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
I don't think "upstream_only" is a good name, but we can certainly tag debian related tasks with "debian", rpm ones with "rpm", etc. Then you can still exclude them as you suggested, without forcing an arbitrary (and maybe changing) upstream/downstream split.

**Comment by evgeni** [comment]
another idea from @mdellweg: split the playbooks to contain just the right things (so e.g. multiple playbooks for content upload).

if you want to implement either of these: feel free -- otherwise I guess it will be done "this year" (no promise)

**Comment by evgeni** [comment]
(and if you're not interested in the result of the recording, you can just call the playbooks with ansible-playbook, so you don't strictly need support for tags in our wrapper)

**Comment by pondrejk** [comment]
> another idea from @mdellweg: split the playbooks to contain just the right things (so e.g. multiple playbooks for content upload).

This sounds cleaner, I'll look into it, thank you
