### ISSUE TITLE
add maintainers for inventory and callback

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#906]
reminder for tomorrows triage

I'd like to add @ares, @xprazak2 and @ezr-ondrej as maintainers for the inventory and callback plugins, so they can merge PRs. either via code owners or just be lazy and do it repo-wide (I'd be okay with that).

**Comment by mdellweg** [comment]
Given their consent, i agree. We need maintainers for those bits. And no need to make it complicated.

**Comment by evgeni** [comment]
the triage has spoken: yes

**Comment by evgeni** [comment]
access has been granted
