### ISSUE TITLE
Foreman inventory does not sync empty groups

### ISSUE THREAD

**Issue by Akasurde** [theforeman/foreman-ansible-modules#919]
_From @rht-jbittner on Mar 27, 2020 11:19_

##### SUMMARY
Foreman dynamic inventory script does not sync empty host groups. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Foreman/Red Hat Satellite dynamic inventory

##### ANSIBLE VERSION

```paste below
All
```

##### STEPS TO REPRODUCE

Create empty host group in Foreman/Red Hat Satellite and sync inventory. Groups without hosts are not synced.

##### EXPECTED RESULTS

All groups synced. Syncing empty host groups is important due to group inheritance. Like in Ansible you can have host group which contains multiple sub groups and define variables on parent group level. This is not possible with current state of the inventory script.

##### ACTUAL RESULTS

Only groups with host synced.

Problem with foreman inventory script is that it does not call Foreman hostgroup API and construct group and membership from hosts instead.

_Copied from original issue: ansible/ansible#68508_

**Comment by Akasurde** [comment]
_From @jctanner on Apr 14, 2020 11:24_

!component =contrib/inventory/foreman.py

**Comment by evgeni** [comment]
@Akasurde FWIW, `contrib/inventory/foreman.py` was not migrated here, only `plugins/inventory/foreman.py` (which is a different! inventory) was. It might have the same bugs, but just blindly assuming that feels wrong ;)

**Comment by evgeni** [comment]
That said, it does look like it applies to our inventory too.

@ares @ezr-ondrej would one of you be able to look into this?

**Comment by ezr-ondrej** [comment]
Sure, I'll try to take a look what is happening there

**Comment by ezr-ondrej** [comment]
@evgeni I can see there is no sync for hostgroups in the sync script, should we add it there before host sync?

**Comment by evgeni** [comment]
@ezr-ondrej I guess that'd be required, yeah. Not sure how it'd play with the `search` parameter though.

Can we get a list of hosts and then only sync all groups (and parents) that those hosts belong to?
