### ISSUE TITLE
installation_medium should be able to handle an os with different versions

### ISSUE THREAD

**Issue by RobVerduijn** [theforeman/foreman-ansible-modules#947]
##### SUMMARY

Currently the installation medium can only attach to the os name and does not consider the possible versions.
ie 
if there is an os named CentOS version 8 and an os named CentOS version 7 it cannot attach to either of them due to the fact that it checks only for the os name which is CentOS in both cases, after which it will fail with an error.
It should be possible to provide versions (major and minor) so that it can decide which os it should attach to.
##### ISSUE TYPE
 - Feature Idea

**Comment by mdellweg** [comment]
The `installation_medium`, as all modules using operatingsystems, does the OS lookup via title and falls back to name. So by being specific enough, you should be able to refer to all of them.

**Comment by RobVerduijn** [comment]
Interesting,
Ah that works, sweet.
however, I double checked, besides seriously digging into  the code, this is not obvious

You might wanna mention this in the documentation.
Untill I read this I considered this module fubar and avoided the use of it.

Rob

**Comment by RobVerduijn** [comment]
It now works, thank you

However it now has the state changed every time it runs even though nothing is changed.

Rob

**Comment by mdellweg** [comment]
Being the one confused initially, would you be willing to improve the documentation?
