### ISSUE TITLE
Discussion: 'Maintenance' module(s)?

### ISSUE THREAD

**Issue by Thulium-Drake** [theforeman/foreman-ansible-modules#965]
##### SUMMARY

It would be nice to have a module that can take some 'generic' commands (just like you would do with hammer) for regular maintenance jobs.

The main reason is to avoid using the shell/command modules, and this could perhaps also allow for some tighter control/feedback.

The commands I can think of off the top of my head (the only ones I wasn't able to code with modules in my role :-) ):

```
hammer content-view purge --organization $ORG --name $CV --count $COUNT
hammer template build-pxe-default
```

What/how do you guys think/feel about this?
##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
As for CV purge, please also look at https://github.com/theforeman/foreman-ansible-modules/pull/958

cc @ehelms who was also looking into "maintenance" tasks for a (this?) collection

**Comment by Thulium-Drake** [comment]
@evgeni thanks for pointing that out! I will give it a shot  :-)

**Comment by evgeni** [comment]
@Thulium-Drake #958 is merged now, and @ehelms started https://github.com/theforeman/foreman-operations-collection/ -- I think we can close this one?

**Comment by Thulium-Drake** [comment]
Yes, sounds good to me!
