### ISSUE TITLE
Handle subnets thats use external IPAM like phpIPAM

### ISSUE THREAD

**Issue by cmeissner** [theforeman/foreman-ansible-modules#966]
We configure our whole foreman server via ansible and we use phpIPAM as external IP address management. Is there a way to configure subnet via ansible which use an external IPAM. We don't found any hints in documentation. On the contrary we found this for IPAM:

```
DHCP
Internal DB
Random DB
EUI-64
None
```

Where `DHCP` is the default. No idea whether the plugin (in this case smart_proxy_ipam) have to/should/can add the needed fields to API.

**Comment by evgeni** [comment]
Are you using https://github.com/grizzthedj/foreman_ipam for the phpIPAM integration?

**Comment by evgeni** [comment]
And if so, what do you enter in the UI when editing a subnet, is there an "IPAM" value for the "IPAM" field now?

**Comment by evgeni** [comment]
Ah, no, that's in core now. Cool.

**Comment by evgeni** [comment]
can you try https://github.com/theforeman/foreman-ansible-modules/pull/967 please?
