### ISSUE TITLE
Vote: Should we add python 3.6 to the test matrix

### ISSUE THREAD

**Issue by mdellweg** [theforeman/foreman-ansible-modules#97]
In the process of #96 this strange behavior occurred:

https://travis-ci.org/theforeman/foreman-ansible-modules/builds/331756267?utm_source=github_status&utm_medium=notification

Since there seem to be subtle differences between python 3.5 and 3.6, the question arises, whether 3.6 should be tested for on travis.

**Comment by ekohl** [comment]
Sounds reasonable to me to keep all supported Python versions in the test matrix and popular versions like the ones shipped in EL7/Debian Latest/Ubuntu LTS (which currently overlap with upstream supported versions).

**Comment by mdellweg** [comment]
Closed as previously anounced...
